import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY)

const data = [
  // ====== 狼与香辛料 (4) ======
  [7373, {name:'赫萝', anime_title:'狼与香辛料', image:'https://s4.anilist.co/file/anilistcdn/character/large/b7373-1BH0gELuZmHD.jpg',
    description:'寄宿在麦穗中的丰收之神——贤狼赫萝。曾在数百年前与一个村庄约定守护丰收，但村民们渐渐忘记了她。在遇到旅行商人罗伦斯后，以"带她回北方故乡约伊兹"为条件与他同行。外表是长有狼耳和尾巴的美少女，实际年龄超过600岁。性格狡黠傲娇，喜欢好酒和苹果，精通商业谈判。',
    traits:['棕发','狼耳','狼尾','贤狼','600岁','傲娇','狡黠','商业头脑','苹果控','酒豪','丰收之神'],
    nicknames:['Holo','赫萝','贤狼','ホロ'], vas:[['小清水亚美','']] }],
  [7374, {name:'克拉夫特·罗伦斯', anime_title:'狼与香辛料', image:'https://s4.anilist.co/file/anilistcdn/character/large/b7374-XeKVCsoW129T.png',
    description:'25岁的独行旅行商人，梦想开一家属于自己的店铺。在帕斯罗村遇到了赫萝，从那天起他的旅程彻底改变。虽然总是抱怨赫萝的任性但内心深处珍视她胜过一切。两人在旅途中发展出一段跨越人神的温柔感情。',
    traits:['灰发','商人','旅行者','精明','温柔','25岁','梦想开店','马匹伙伴','与狼同行'],
    nicknames:['Kraft Lawrence','罗伦斯','クラフト・ロレンス'], vas:[['福山润','']] }],
  [7376, {name:'诺拉·艾伦特', anime_title:'狼与香辛料', image:'https://s4.anilist.co/file/anilistcdn/character/large/b7376-Hc7DpDQj6I31.png',
    description:'年轻的牧羊女，受雇于教会担任牧羊人。与一只训练有素的大型牧羊犬艾尼克为伴。在旅途中与罗伦斯和赫萝相遇，卷入了关于走私和教会权力的复杂事件。',
    traits:['棕发','牧羊女','教会','善良','大型牧羊犬','少女'], nicknames:['Nora Arendt','诺拉','ノーラ'], vas:[['暂未收录','']] }],
  [7375, {name:'库洛艾', anime_title:'狼与香辛料', image:'https://s4.anilist.co/file/anilistcdn/character/large/b7375-Fl8ZYFMB1MPP.png',
    description:'帕斯罗村的居民，与罗伦斯有商业往来。在故事初期登场，是罗伦斯和赫萝相遇的见证者。', traits:['棕发','帕斯罗村','村民','见证者'], nicknames:['Chloe','库洛艾'], vas:[['暂未收录','']] }],

  // ====== 魔法少女小圆 (6) ======
  [37832, {name:'鹿目圆', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b37832-lzVj5IkUciLd.jpg',
    description:'温柔善良的初二少女，故事的起点和终点。她不断被询问是否愿意成为魔法少女，而每一次轮回她的愿望都在改变世界。在无数次轮回后做出了那个震撼所有观众的选择。粉发双马尾的温柔外表下承载了整个宇宙的希望。',
    traits:['粉发','双马尾','初二','温柔','善良','魔法少女','爱','终极牺牲','因果律'],
    nicknames:['Madoka Kaname','鹿目圆','Madoka','圆神','鹿目まどか'], vas:[['悠木碧','']] }],
  [38005, {name:'晓美焰', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b38005-T3NR8p2f021x.jpg',
    description:'从未来不断回溯时间的魔法少女。为了拯救小圆经历了上百次轮回，从胆小的病弱少女成长为冷酷强大的战士。使用时间停止和各种重火器战斗。所有这些只是为了再见她一次。',
    traits:['黑发','长发','时间停止','轮回','冷酷','强大','眼镜','痴情','火箭筒','黑长直'],
    nicknames:['Homura Akemi','晓美焰','Homura','ほむら','焰魔'], vas:[['斋藤千和','']] }],
  [38395, {name:'美树沙耶香', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b38395-d24OayatTB5h.jpg',
    description:'小圆的同班同学和好友，元气满满的蓝发少女。为了治愈青梅竹马恭介的手臂而成为魔法少女。但在理想与现实的反差中逐渐绝望，最终成为了自己曾经最讨厌的存在。故事中最令人心碎的角色之一。',
    traits:['蓝发','短发','元气','正义','骑士','魔法少女','绝望','魔女化','剑术'],
    nicknames:['Sayaka Miki','美树沙耶香','Sayaka','さやか'], vas:[['喜多村英梨','']] }],
  [38194, {name:'巴麻美', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b38194-gnlnx4XN4HYP.jpg',
    description:'小圆和沙耶香的前辈魔法少女，使用丝带和燧发枪战斗。外表温柔优雅的学姐，其实内心极度渴望同伴和认可。第三次轮回中的名场面让所有观众铭记。红茶和蛋糕是她优雅的标签。',
    traits:['金发','卷发','学姐','优雅','丝带','燧发枪','红茶','孤独','魔法少女前辈'],
    nicknames:['Mami Tomoe','巴麻美','Mami','学姐','マミ'], vas:[['水桥香织','']] }],
  [40006, {name:'佐仓杏子', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b40006-zOwYYimuiO3m.png',
    description:'来自邻近城市的魔法少女，使用多节长枪战斗。因为过去的经历信奉"只为自己的愿望而战"的信条。一度与沙耶香对立但最终成为她最重要的人。贪吃货，尤其是苹果和Pocky。',
    traits:['红发','马尾','长枪','贪吃','自私信条','冷酷外表','温柔内里','苹果','傲娇'],
    nicknames:['Kyouko Sakura','佐仓杏子','Kyouko','杏子'], vas:[['野中蓝','']] }],
  [38566, {name:'丘比', anime_title:'魔法少女小圆', image:'https://s4.anilist.co/file/anilistcdn/character/large/b38566-XzE2iqAodRQK.jpg',
    description:'可爱的白色猫型生物，邀请少女们成为魔法少女。从不撒谎——但也从不主动说出全部的真相。为了收集感情能量拯救宇宙而不择手段。是表面可爱实则冷酷的"传销"机器。名言是"和我签订契约，成为魔法少女吧！"。',
    traits:['白色','猫型','外星生物','理性','无感情','契约','不撒谎','只说一半','可爱','反派','传销'],
    nicknames:['Kyuubey','丘比','QB','キュゥべえ','传销兽'], vas:[['加藤英美里','']] }],

  // ====== 青春猪头少年 (5) ======
  [127222, {name:'樱岛麻衣', anime_title:'青春猪头少年不会梦到兔女郎学姐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png',
    description:'峰之原高中的三年级学姐，知名女演员。因"青春期综合征"而逐渐从人们的视野中消失——没有人能再看见她。直到她在图书馆穿着兔女郎装测试是否还有人能看到自己时遇到了咲太。外表毒舌傲娇但内心极度温柔。',
    traits:['黑发','兔女郎','女演员','学姐','毒舌','傲娇','温柔','青春期综合征','消失','美丽'],
    nicknames:['Mai Sakurajima','樱岛麻衣','Mai','麻衣学姐'], vas:[['濑户麻沙美','']] }],
  [127221, {name:'梓川咲太', anime_title:'青春猪头少年不会梦到兔女郎学姐', image:'https://s4.anilist.co/file/anilistcdn/character/large/n127221-Wxg4xFtW4kaJ.png',
    description:'峰之原高中二年级学生。因为"送医事件"被全校误解和避之不及，但本人完全不以为意。对麻衣一见钟情后展开了直球追求攻势。总能一针见血地指出问题本质，帮助陷入青春期综合征的少女们。名言是"我想确认你的存在"。',
    traits:['黑发','高中生','直球','温柔','被误解','青春期综合征解决者','情商高','天然撩'],
    nicknames:['Sakuta Azusagawa','梓川咲太','Sakuta','咲太'], vas:[['石川界人','']] }],
  [127613, {name:'梓川花枫', anime_title:'青春猪头少年不会梦到兔女郎学姐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b127613-LBtFkMJfUWpg.png',
    description:'咲太的妹妹，因遭受校园霸凌而患上青春期综合征——身体出现大片不明原因的伤痕。在哥哥的保护下逐渐恢复。是咲太为了保护麻衣而奋不顾身的原动力之一。',
    traits:['棕发','妹妹','校园霸凌','青春期综合征','被保护','伤痕','成长'],
    nicknames:['Kaede Azusagawa','梓川花枫','Kaede','花枫'], vas:[['暂未收录','']] }],
  [127633, {name:'双叶理央', anime_title:'青春猪头少年不会梦到兔女郎学姐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b127633-FcCwWK5sQRhK.png',
    description:'咲太的同班同学，科学部的唯一成员。理性至上的理科少女，是咲太唯一可以商量青春期综合征问题的智囊。自己也陷入了"两个人格分裂"的青春期综合征。暗恋国见佑真。',
    traits:['黑发','眼镜','理科女','理性','智囊','科学部','人格分裂','自拍照','青春期综合征'],
    nicknames:['Rio Futaba','双叶理央','Rio','理央'], vas:[['暂未收录','']] }],
  [127840, {name:'古贺朋绘', anime_title:'青春猪头少年不会梦到兔女郎学姐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b127840-z2LUox2R2Ivg.jpg',
    description:'咲太的学妹，陷入了"同一日不断重复"的青春期综合征。为了逃避现实而假装与咲太交往。性格活泼可爱但内心对人际关系缺乏安全感。',
    traits:['棕发','学妹','假交往','时间循环','青春期综合征','活泼','缺乏安全感'],
    nicknames:['Tomoe Koga','古贺朋绘','Tomoe','朋绘'], vas:[['暂未收录','']] }],

  // ====== 为美好的世界献上祝福 (4) ======
  [89364, {name:'佐藤和真', anime_title:'为美好的世界献上祝福', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89364-7Th8Tv1XKJtt.png',
    description:'被拖拉机吓死后转生到异世界的尼特族。转生女神让他带一件物品去异世界，他选择了嘲笑他的女神阿库娅本人从这里开始人生就全是坑。拥有鬼畜级的幸运值和不正经的战斗方式（偷窃术→偷内裤）。带领着三个坑货女神/废柴队友在异世界摸爬滚打。',
    traits:['棕发','尼特族','转生者','鬼畜','高幸运','吐槽役','冒险者','偷窃术','智障队友','异世界','老司机'],
    nicknames:['Kazuma Satou','佐藤和真','Kazuma','鬼畜和真','人渣真'], vas:[['福岛润','']] }],
  [89362, {name:'阿库娅', anime_title:'为美好的世界献上祝福', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89362-ibkc0eoECaW1.png',
    description:'水之女神，被和真转生时拉下水一起带到异世界。拥有极强的治疗和净化能力但这些能力完全浪费在她的智障行为上。每次作死搞事被和真骂就会哭出声而且哭声大到召唤洪水。全剧智商地板兼搞笑担当。属性和数值被和真拿去当打牌素材。',
    traits:['蓝发','女神','智障','治疗','净化','爱哭','宴会艺人','智商地板','搞笑担当','水之女神'],
    nicknames:['Aqua','阿库娅','アクア','智障女神','废物女神'], vas:[['雨宫天','']] }],
  [89363, {name:'达克妮斯', anime_title:'为美好的世界献上祝福', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89363-mm21Ll4NegUD.png',
    description:'十字骑士团的骑士——拥有出色的防御力但攻击命中率为零。因为是个抖M。非常非常严重的受虐狂，战斗时甚至会因为被怪物打得太爽而感动。真实身份是名门贵族大小姐拉拉蒂娜。外表金发碧眼的淑女内在已经完全崩坏。',
    traits:['金发','碧眼','骑士','抖M','贵族','攻击打不中','盾牌','防御力MAX','肌肉控','大小姐'],
    nicknames:['Darkness','达克妮斯','Lalatina','ダクネス','拉拉蒂娜','十字骑士'], vas:[['茅野爱衣','']] }],
  [89361, {name:'惠惠', anime_title:'为美好的世界献上祝福', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png',
    description:'红魔族的大魔法使，只会使用爆裂魔法——吟唱完一发后立刻倒地动弹不得。对爆裂魔法有着近乎信仰般的执念，拒绝学习任何其他魔法。戴着标志性的尖帽子和红色魔法杖。每天不爆裂一次就浑身不舒服。名言是"Explosion！"',
    traits:['黑发','红魔族','爆裂魔法','贫乳','一发倒','中二病','尖帽子','眼罩','魔法杖','Explosion','每日爆裂'],
    nicknames:['Megumin','惠惠','めぐみん','爆裂魔导师','红魔族第一天才'], vas:[['高桥李依','']] }],

  // ====== 冰菓 (4) ======
  [55131, {name:'折木奉太郎', anime_title:'冰菓', image:'https://s4.anilist.co/file/anilistcdn/character/large/b55131-ypodHQCyHbzD.png',
    description:'神山高中古典部成员，奉行"节能主义"——不必要的事不做，必要的事尽快做。拥有极强的推理能力但极度怕麻烦。被千反田爱瑠那句"我很好奇！"拖入了无数推理事件中。灰色头发、死鱼眼的节能系高中生。',
    traits:['棕发','死鱼眼','节能主义','推理天才','怕麻烦','古典部','低能耗','被拖进事件'],
    nicknames:['Houtarou Oreki','折木奉太郎','Oreki','节能君'], vas:[['中村悠一','']] }],
  [55133, {name:'千反田爱瑠', anime_title:'冰菓', image:'https://s4.anilist.co/file/anilistcdn/character/large/b55133-S7lRrP0gKXpX.png',
    description:'神山高中古典部部长，富农家的大小姐。拥有无边无际的好奇心，遇到有趣的事就会睁大紫色的大眼睛说"我很好奇！"。这句口头禅每次都会把奉太郎拖下水。但她的记忆中隐藏着关于舅舅的沉重秘密。',
    traits:['黑发','紫瞳','大小姐','好奇心','我很好奇','古典部','优雅','记忆力','八卦眼'],
    nicknames:['Eru Chitanda','千反田爱瑠','Chitanda','千反田','我很好奇'], vas:[['佐藤聪美','']] }],
  [55135, {name:'福部里志', anime_title:'冰菓', image:'https://s4.anilist.co/file/anilistcdn/character/large/b55135-rSgLOX86JRSO.png',
    description:'古典部成员，自称"数据库"——拥有丰富杂学知识但不能将它们转化为结论。随身携带着不知装了什么的束口袋。性格开朗，与奉太郎是好友。口头禅是"这只是个数据库"。',
    traits:['棕发','数据库','杂学','开朗','束口袋','古典部','朋友'],
    nicknames:['Satoshi Fukube','福部里志','Fukube','数据库'], vas:[['阪口大助','']] }],
  [55137, {name:'伊原摩耶花', anime_title:'冰菓', image:'https://s4.anilist.co/file/anilistcdn/character/large/b55137-PO5CLLnbTwyg.png',
    description:'古典部成员，也是漫画研究会成员。性格认真火爆，对奉太郎的节能主义嗤之以鼻。暗恋福部里志。虽然个头娇小但存在感极强。',
    traits:['棕发','娇小','火爆','漫画研究会','古典部','暗恋','认真'],
    nicknames:['Mayaka Ibara','伊原摩耶花','Ibara','摩耶花'], vas:[['暂未收录','']] }],

  // ====== 龙与虎 (5) ======
  [12064, {name:'逢坂大河', anime_title:'龙与虎', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12064-7PDN3ylIeAZn.png',
    description:'掌中老虎——名字中"大河"音近"Tiger"加上她的暴躁性格和极小身材。是学校里人人畏惧的"最强最凶"美少女。与龙儿相遇后开始了一段以互相助攻恋爱为名的同居生活。外表凶猛内心极度敏感脆弱。被称为"傲娇系的教科书"。',
    traits:['棕发','娇小','掌中老虎','傲娇','暴力','敏感','初恋','同居','料理','虎纹'],
    nicknames:['Taiga Aisaka','逢坂大河','Taiga','掌中老虎','大河酱'], vas:[['钉宫理惠','']] }],
  [12295, {name:'高须龙儿', anime_title:'龙与虎', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12295-d45uTNeJHuus.png',
    description:'长相凶恶（遗传自黑道叔叔）的温柔少年。擅长料理和家务，一手包办母亲和自己的生活。因为外表被全校误解为不良少年但内心比谁都温柔。与大河同住后成为她的专属保姆/厨师/护卫。',
    traits:['黑发','面相凶恶','温柔','家务全能','料理高手','被误解','母亲缺乏','虎的守护者'],
    nicknames:['Ryuuji Takasu','高须龙儿','Ryuuji','龙儿'], vas:[['间岛淳司','']] }],
  [12305, {name:'栉枝实乃梨', anime_title:'龙与虎', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12305-AdKOcp0az9mq.jpg',
    description:'大河的闺蜜，垒球部主力。永远充满活力的元气少女，用夸张的肢体动作和说冷笑话来掩饰自己真实的感情。龙儿暗恋的对象，但她的心似乎另有所属。',
    traits:['红发','元气','垒球','运动少女','冷笑话','掩盖感情','闺蜜','活力'],
    nicknames:['Minori Kushieda','栉枝实乃梨','Minori','实乃梨'], vas:[['堀江由衣','']] }],
  [13725, {name:'川岛亚美', anime_title:'龙与虎', image:'https://s4.anilist.co/file/anilistcdn/character/large/b13725-Vk30kjvVT82z.png',
    description:'转学而来的兼职模特，外表甜美可爱的天使——但这是表面人格。真实的她毒舌腹黑，只有龙儿和大河知道她的真面目。在故事中成为了重要的催化剂和观察者。',
    traits:['蓝发','模特','天使外表','腹黑','毒舌','演技','转学生','催化剂'],
    nicknames:['Ami Kawashima','川岛亚美','Ami','亚美酱'], vas:[['喜多村英梨','']] }],
  [12306, {name:'北村佑作', anime_title:'龙与虎', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12306-Nb1orOh4UkpT.png',
    description:'龙儿的死党，学生会副会长。眼镜加短发的清爽好青年。曾经为了追随心上人（学生会长）而染金发大闹学生会。大河最初的爱慕对象。',
    traits:['棕发','眼镜','学生会','清爽','死党','好青年','金发时期'],
    nicknames:['Yuusaku Kitamura','北村佑作','Kitamura','北村'], vas:[['暂未收录','']] }],

  // ====== 中二病也要谈恋爱 (5) ======
  [65865, {name:'小鸟游六花', anime_title:'中二病也要谈恋爱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b65865-AC0ru7cDXUgK.png',
    description:'自称"邪王真眼"的现役中二病少女。右眼戴着眼罩，左手缠着绷带（全是假的）。在车站天台上做着各种中二病pose时遇到了"前中二病"勇太。相信在"不可视境界线"的另一端能找到父亲。从中二病开始了一段笨拙又甜蜜的初恋。',
    traits:['黑发','眼罩','邪王真眼','中二病','呆毛','绷带','少女','寻找父亲','初恋','想象力丰富'],
    nicknames:['Rikka Takanashi','小鸟游六花','Rikka','六花','邪王真眼'], vas:[['内田真礼','']] }],
  [65863, {name:'富樫勇太', anime_title:'中二病也要谈恋爱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b65863-blMgFqD1EnPs.png',
    description:'前中二病患者的普通高中生，初中时的黑历史是自称"Dark Flame Master"。转学到一个没人认识的地方洗清过去却被六花发现了他的中二病黑历史。虽然试图过普通生活但被六花拖回了中二世界。',
    traits:['棕发','前中二病','Dark Flame Master','黑历史','被拖下水','吐槽','六花照顾者'],
    nicknames:['Yuuta Togashi','富樫勇太','Yuuta','Dark Flame Master'], vas:[['福山润','']] }],
  [67215, {name:'凸守早苗', anime_title:'中二病也要谈恋爱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b67215-J87mEugyhVRO.png',
    description:'六花的中二病徒弟，自称六花的"servant"。把长长的双马尾当成传说中的武器"Mighty Blow Hammer"挥舞。性格活泼过头的中二病少女，与学姐丹生谷森夏是死对头。',
    traits:['金发','双马尾','中二病','六花仆人','Mighty Blow','锤子','活泼','死对头'],
    nicknames:['Sanae Dekomori','凸守早苗','Dekomori','デコもり'], vas:[['上坂堇','']] }],
  [65871, {name:'丹生谷森夏', anime_title:'中二病也要谈恋爱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b65871-yuJ1aq2vynvC.png',
    description:'勇太的同班同学，现充大小姐——实则也是前中二病患者。初中时自创了"Mori Summer"的魔法少女人设在网上至今流传。极度恐惧自己的黑历史曝光，为此与知道秘密的凸守早苗长期斗智斗勇。',
    traits:['棕发','大小姐','前中二病','Mori Summer','黑历史恐惧','现充','傲娇'],
    nicknames:['Shinka Nibutani','丹生谷森夏','Nibutani','Mori Summer'], vas:[['赤崎千夏','']] }],
  [67213, {name:'五月七日小茴香', anime_title:'中二病也要谈恋爱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b67213-ullAaqYtUG1N.png',
    description:'比勇太高一年级的学姐，六花的社团成员。有随时随地睡着——甚至站着也能睡的特异体质。性格悠哉随和，是社团中最年长的存在却最没有存在感。抱枕和枕头是她的随身物品。',
    traits:['棕发','随时随地睡着','枕头','学姐','悠哉','社团成员','嗜睡症'],
    nicknames:['Kumin Tsuyuri','五月七日小茴香','Kumin','睡觉学姐'], vas:[['暂未收录','']] }],

  // ====== 凉宫春日的忧郁 (5) ======
  [251, {name:'凉宫春日', anime_title:'凉宫春日的忧郁', image:'https://s4.anilist.co/file/anilistcdn/character/large/b251-8DTaCNkSvBQ8.png',
    description:'高中一年级的少女，对"不可思议的人事物"以外的一切不感兴趣。在开学的自我介绍中说"未来人、外星人、超能力者来找我吧！"而成立SOS团。无意识中拥有改变世界的力量——她的想法能扭曲现实本身。性格唯我独尊但对团员们有着深深的依恋。',
    traits:['棕发','黄发带','唯我独尊','神','现实扭曲者','SOS团团长','元气','任性','孤独'],
    nicknames:['Haruhi Suzumiya','凉宫春日','Haruhi','团长','涼宮ハルヒ'], vas:[['平野绫','']] }],
  [252, {name:'阿虚', anime_title:'凉宫春日的忧郁', image:'https://s4.anilist.co/file/anilistcdn/character/large/b252-2V9wYXSAktsX.png',
    description:'SOS团唯一的普通人（？），本名不详。被春日拉入SOS团成为她的专属吐槽役和"奴隶"。口头禅是"やれやれ"。虽然嘴上抱怨但从不缺席任何SOS团的活动，是唯一能与春日平等对话的人——也是春日最在意的人。',
    traits:['棕发','普通人','吐槽役','やれやれ','旁观者','凉宫春日的吐槽对象','第一人称叙述者'],
    nicknames:['Kyon','阿虚','キョン','吐槽之王'], vas:[['杉田智和','']] }],
  [249, {name:'长门有希', anime_title:'凉宫春日的忧郁', image:'https://s4.anilist.co/file/anilistcdn/character/large/b249-2YImP6IQTe8t.png',
    description:'SOS团所属的文艺部部员，眼镜加短发的冷面少女。真实身份是宇宙统合思念体的外星人——被派来观察凉宫春日。拥有近乎无限的信息操控能力但极度寡言。唯一的爱好是看书。在某个事件中展现了对阿虚超越任务范畴的情感。眼镜和没有眼镜是有希的两个版本。',
    traits:['紫发','短发','眼镜','外星人','寡言','看书','观察者','无表情','情报操控','文学少女'],
    nicknames:['Yuki Nagato','长门有希','Yuki','大萌神','長門有希'], vas:[['茅原实里','']] }],
  [253, {name:'朝比奈实玖瑠', anime_title:'凉宫春日的忧郁', image:'https://s4.anilist.co/file/anilistcdn/character/large/b253-opGQ1w4AdkEK.jpg',
    description:'SOS团的"吉祥物"，来自未来的时间旅行者。比阿虚高一年级的前辈，被春日以"萌元素"为由强行拉入社团。性格胆小怕生，经常被春日强迫cosplay各种服装。用眼泪和可爱征服了所有团员（和读者）。实际在未来是非常干练的女性。',
    traits:['棕发','巨乳','未来人','时间旅行','吉祥物','胆小','cosplay','写真','可爱','萌元素'],
    nicknames:['Mikuru Asahina','朝比奈实玖瑠','Mikuru','みくる','实玖瑠'], vas:[['后藤邑子','']] }],
  [254, {name:'古泉一树', anime_title:'凉宫春日的忧郁', image:'https://s4.anilist.co/file/anilistcdn/character/large/b254-ZyIHZUY6yz4W.png',
    description:'转学到北高的美少年，SOS团所属的超能力者（机关成员）。在春日情绪不稳定时会在闭锁空间中战斗。永远保持着优雅的微笑，无论面对什么事都能用从容的态度化解。和阿虚形成"超能力者×普通人"组合。',
    traits:['棕发','美少年','超能力者','微笑','机关','转学生','闭锁空间','优雅'],
    nicknames:['Itsuki Koizumi','古泉一树','Koizumi','古泉'], vas:[['小野大辅','']] }],

  // ====== 黑执事 (4) ======
  [12531, {name:'西雅尔·凡多姆海威', anime_title:'黑执事', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12531-joBTjTP3fonc.png',
    description:'凡多姆海威伯爵家的13岁当主，被称为"女王的看门犬"——暗中处理维多利亚女王地下世界的肮脏任务。在父母被杀后与恶魔塞巴斯蒂安签订了灵魂契约。右眼戴着标记契约的眼罩。外表是纯真无邪的少年但内心被复仇吞噬。',
    traits:['蓝发','眼罩','13岁','伯爵','女王的看门犬','灵魂契约','复仇','少年','优雅','阴暗面'],
    nicknames:['Ciel Phantomhive','西雅尔·凡多姆海威','Ciel','夏尔','少爷'], vas:[['坂本真绫','']] }],
  [10863, {name:'塞巴斯蒂安·米卡艾利斯', anime_title:'黑执事', image:'https://s4.anilist.co/file/anilistcdn/character/large/b10863-DsfonbP2CATa.png',
    description:'凡多姆海威家的执事，真实身份是恶魔。与西雅尔签订契约后以完美的执事姿态为他效劳——打理庄园、泡红茶、解决一切敌人。全知全能的美男子。契约的报酬是西雅尔的灵魂。口头禅是"我是恶魔，也是执事"。',
    traits:['黑发','红色眼瞳','恶魔','完美执事','全能','红茶','黑色燕尾服','银器','优雅','契约','忠诚于少爷'],
    nicknames:['Sebastian Michaelis','塞巴斯蒂安','Sebastian','384','恶魔执事'], vas:[['小野大辅','']] }],
  [12960, {name:'格雷尔·萨特克利夫', anime_title:'黑执事', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12960-TU6by6WTq5By.png',
    description:'红发的死神，初登场时伪装成懦弱的仆人实则是疯狂的死神。使用一把经过改造的电锯死神镰刀。对塞巴斯蒂安有着狂热的痴迷。性格戏剧化、浮夸到极致。特色是标志性的鲨鱼齿和红色长袍。',
    traits:['红发','死神','鲨鱼齿','电锯镰刀','疯狂','戏剧化','塞巴斯蒂安痴迷','浮夸','红袍'],
    nicknames:['Grell Sutcliff','格雷尔','Grell','死神格雷尔'], vas:[['福山润','']] }],
  [79607, {name:'爱德华·米德福德', anime_title:'黑执事', image:'https://s4.anilist.co/file/anilistcdn/character/large/b79607-tTNBPbPwsQyZ.jpg',
    description:'西雅尔的表兄兼同学，剑术高手。对西雅尔极为关怀和爱护，希望他能过上正常的生活。性格正直勇敢但在某些事情上过分天真。',
    traits:['金发','剑术','表兄','正直','同学','爱护少爷'], nicknames:['Edward Midford','爱德华'], vas:[['暂未收录','']] }],

  // ====== Angel Beats (5) ======
  [22370, {name:'仲村由理', anime_title:'Angel Beats', image:'https://s4.anilist.co/file/anilistcdn/character/large/b22370-pNQxFEv1K7lS.jpg',
    description:'死后世界战线（SSS）的领袖，代号"Yurippe"。领导着死后世界的少年少女们对抗天使（学生会长立华奏）。枪法出众的战略天才。外表强势坚定但内心深处藏着对生前命运的愤怒和悲伤。总是在伙伴们面前展现出最强大的一面。',
    traits:['紫发','首领','Yurippe','枪械','强气','战略天才','死后世界','SSS','悲伤过去'],
    nicknames:['Yuri Nakamura','仲村由理','Yurippe','由理'], vas:[['樱井浩美','']] }],
  [22369, {name:'立华奏', anime_title:'Angel Beats', image:'https://s4.anilist.co/file/anilistcdn/character/large/b22369-zC7OgGbfO7b6.jpg',
    description:'死后世界的学生会长，被称为"天使"。使用Hand Sonic护盾和超高速战斗能力。初看是冷酷无表情的敌人但实际上是守护这个世界的存在。最爱吃学生会室里的麻婆豆腐。她那句"谢谢你"是无数粉丝心中最深的感动。',
    traits:['银发','金色眼瞳','天使','学生会长','无表情','Hand Sonic','麻婆豆腐','守护','温柔'],
    nicknames:['Kanade Tachibana','立华奏','Kanade','天使','奏'], vas:[['花泽香菜','']] }],
  [24502, {name:'音无结弦', anime_title:'Angel Beats', image:'https://s4.anilist.co/file/anilistcdn/character/large/b24502-TJE8JeOERvj0.jpg',
    description:'在死后世界醒来时失去了所有记忆的少年。唯一的线索是个空钱包和学生证。最初被由理拉入 SSS 但逐渐开始怀疑对抗天使是否正确。与奏的相遇改变了一切。生前的身份与奏有着令人心碎的因果。',
    traits:['红发','失忆','SSS','怀疑','善良','关键人物','与奏因果','死后世界'],
    nicknames:['Yuzuru Otonashi','音无结弦','Otonashi','音无'], vas:[['神谷浩史','']] }],
  [24515, {name:'由依', anime_title:'Angel Beats', image:'https://s4.anilist.co/file/anilistcdn/character/large/b24515-4v85Z9CqCe0Y.png',
    description:'SSS的辅助成员——负责在战场中场唱歌为前线战士加油的少女乐队"Girls Dead Monster"的狂热粉丝。粉红色的头发双马尾充满元气的少女。生前因瘫痪从未下过床，死后世界是她第一次能自由奔跑的地方。她与日向的故事看哭了无数人。',
    traits:['粉发','双马尾','元气','偶像','Girls Dead Monster','生前瘫痪','自由','梦想','结婚愿望'],
    nicknames:['Yui','由依','ユイ','Yui-nyan'], vas:[['喜多村英梨','']] }],
  [24503, {name:'日向秀树', anime_title:'Angel Beats', image:'https://s4.anilist.co/file/anilistcdn/character/large/b24503-aMw9BnXmEVrP.png',
    description:'SSS的核心成员，音无在死后世界最早结识的朋友。棒球高手，爱吃炒面面包的普通好青年。与由依的感情线是整部剧最催泪的支线之一——对未来许下了"如果有来世一定娶你"的承诺。',
    traits:['蓝发','棒球','炒面面包','音无朋友','SSS','温柔','由依故事线'],
    nicknames:['Hideki Hinata','日向秀树','Hinata','日向'], vas:[['暂未收录','']] }],
]

let count = 0
for (const [id, d] of data) {
  const { error } = await supabase.from('characters').upsert({
    id, name: d.name, anime_title: d.anime_title, image: d.image,
    description: d.description, traits: d.traits, nicknames: d.nicknames,
  }, { onConflict: 'id' })
  if (d.vas) {
    await supabase.from('voice_actors').delete().eq('character_id', id)
    for (const [name, img] of d.vas) {
      await supabase.from('voice_actors').insert({ character_id: id, name, image: img || '', language: '日语' })
    }
  }
  process.stdout.write(error ? '❌' : '+')
  count++
}
console.log('\n重建 search_text...')
const { data: chars } = await supabase.from('characters').select('id, name, anime_title, nicknames, traits, voice_actors(name)')
for (const c of chars||[]) {
  const st = [c.name, c.anime_title||'', ...(c.nicknames||[]), ...(c.traits||[]), ...(c.voice_actors||[]).map(v=>v.name)].join(' ')
  await supabase.from('characters').update({ search_text: st }).eq('id', c.id)
}
console.log('✅', count, '个角色')
