import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY)

const data = [
  // ====== 银魂 (4) ======
  [672, {name:'坂田银时', anime_title:'银魂', image:'https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png',
    description:'万事屋的老板，银发自然卷的死鱼眼武士。曾经是被称为"白夜叉"的攘夷志士，现在则是个嗜糖如命、拖欠房租、整天看Jump的废柴大叔。但每当重要的人陷入危机时，那洞爷湖木刀便会重新展现出白夜叉的实力。名言是"与其想着怎样去死，不如想想怎样活下去"。',
    traits:['银发','自然卷','死鱼眼','甜食控','糖尿病边缘','白夜叉','洞爷湖','废柴大叔','万事屋','Jump读者'],
    nicknames:['Gintoki Sakata','坂田银时','Gintoki','银桑','白夜叉'], vas:[['杉田智和','']] }],
  [674, {name:'神乐', anime_title:'银魂', image:'https://s4.anilist.co/file/anilistcdn/character/large/b674-w8wCh0A5Qa8R.png',
    description:'万事屋的夜兔族少女，宇宙最强的战斗种族后裔。外表是可爱的团子头少女但拥有恐怖的怪力。饭量无敌大吃穷银时。喜欢腌昆布，用大伞当武器。口头禅是"阿噜"。毒舌程度与银时不相上下。',
    traits:['橘红发','团子头','夜兔族','怪力','大食量','腌昆布','伞武器','毒舌','可爱暴力'],
    nicknames:['Kagura','神乐','かぐら','阿噜'], vas:[['钉宫理惠','']] }],
  [673, {name:'志村新八', anime_title:'银魂', image:'https://s4.anilist.co/file/anilistcdn/character/large/b673-nScArSMt85kd.jpg',
    description:'万事屋的眼镜（本体）。人类部分是附带品。剑术道场的继承人，实力意外地强——但绝大多数时候都在疯狂吐槽银时和神乐的荒唐行为。唯一清醒的常识人。最喜欢的偶像是寺门通。',
    traits:['黑发','眼镜','吐槽役','剑术','寺门通粉丝','常识人','道场继承人'],
    nicknames:['Shinpachi Shimura','志村新八','Shinpachi','新八','眼镜本体'], vas:[['阪口大助','']] }],
  [2651, {name:'定春', anime_title:'银魂', image:'https://s4.anilist.co/file/anilistcdn/character/large/n2651-e8BTqVZl8lK2.jpg',
    description:'万事屋饲养的巨大白色宠物狗，实际是宇宙生物。身材巨大能把人吞进嘴里。喜欢咬银时的头。虽然外表凶猛但非常忠诚和可爱。', traits:['白色','巨型犬','宇宙生物','咬头','宠物','可爱'], nicknames:['Sadaharu','定春'], vas:[['暂未收录','']] }],

  // ====== 全职猎人 (5) ======
  [30, {name:'小杰·富力士', anime_title:'全职猎人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg',
    description:'12岁的少年猎人，鲸鱼岛出身。拥有超强的野性直觉和无限的成长潜力。为了寻找父亲金而踏上猎人之路。性格单纯天真但面对敌人时展现出令人震惊的黑暗面——"因为我比你强"。念能力为强化系。',
    traits:['黑发','刺猬头','12岁','强化系','猎人','正义','野性直觉','单纯','黑暗面','寻找父亲'],
    nicknames:['Gon Freecss','小杰','Gon','杰·富力士'], vas:[['潘惠美','']] }],
  [27, {name:'奇犽·揍敌客', anime_title:'全职猎人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg',
    description:'杀手家族揍敌客的继承人，小杰最好的朋友。银发的天才少年。从出生被训练成完美的杀人机器却选择背叛家族去寻找自己的人生。使用电光石火般的暗杀术和溜溜球作为武器。念能力变化系——将电转化为自己的力量。',
    traits:['银发','杀手家族','天才','溜溜球','变化系','电击','嗜甜','小杰挚友','背叛家族'],
    nicknames:['Killua Zoldyck','奇犽','Killua','奇犽·揍敌客'], vas:[['伊濑茉莉也','']] }],
  [28, {name:'酷拉皮卡', anime_title:'全职猎人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png',
    description:'窟卢塔族最后的幸存者，全族人的眼球被幻影旅团挖走制成"火红眼"收藏品。以复仇为动力成为猎人。念能力具现化系——创造了只能对幻影旅团使用的绝对契约锁链。平时冷静理性但在面对旅团时双眼会变得火红而失去理智。',
    traits:['金发','火红眼','窟卢塔族','复仇','锁链','具现化系','冷静','幻影旅团追杀者'],
    nicknames:['Kurapika','酷拉皮卡','クラピカ'], vas:[['泽城美雪','']] }],
  [29, {name:'雷欧力·帕拉丁奈特', anime_title:'全职猎人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b29-RgzoSeKmDYzl.jpg',
    description:'想要成为医生的猎人，四人组中最年长的成员。外表像30岁的大叔但实际只有19岁。贪财好色但内心极为善良，成为医生的动机是无法忘记因病逝去的朋友。念能力放出系——通过隔空打出的拳头进行治疗。',
    traits:['黑发','大叔脸','19岁','爱财','好色','医生志愿','放出系','善良','大哥'],
    nicknames:['Leorio Paradinight','雷欧力','Leorio','大叔'], vas:[['藤原启治','']] }],
  [26, {name:'金·富力士', anime_title:'全职猎人', image:'https://s4.anilist.co/file/anilistcdn/character/large/26-VpZXIwOdcz8p.jpg',
    description:'小杰的父亲，世界五大念能力者之一。身为二星猎人却从不履行猎人的职责，是个彻底的不负责任父亲——把小杰留给鲸鱼岛的阿姨后就消失了。但所有认识他的人都对他赞誉有加。Greed Island的创造者之一。',
    traits:['黑发','二星猎人','念能力者','不负责任父亲','天才','Greed Island','世界五大'],
    nicknames:['Ging Freecss','金·富力士','Ging','金'], vas:[['暂未收录','']] }],

  // ====== 排球少年 (5) ======
  [64769, {name:'日向翔阳', anime_title:'排球少年', image:'https://s4.anilist.co/file/anilistcdn/character/large/b64769-WoWlCMLLgJ14.png',
    description:'乌野高中排球部的"小巨人"——虽然身高只有162cm但拥有惊人的弹跳力。在初中的最后一场比赛中被影山彻底击败后发誓要超越他，结果两人进了同一所高中。以野性的速度和跳跃弥补身高不足，是最强的"最強の囮"。',
    traits:['橙发','162cm','弹跳力','小巨人','快攻','囮役','元气','不服输'],
    nicknames:['Shouyou Hinata','日向翔阳','Hinata','小不点'], vas:[['村濑步','']] }],
  [64771, {name:'影山飞雄', anime_title:'排球少年', image:'https://s4.anilist.co/file/anilistcdn/character/large/b64771-BuCVs7B8bBdh.png',
    description:'乌野高中排球部的天才二传手，被称为"球场上的王者"——但是个暴君。拥有精准到毫米的托球技术和极高的排球智商。过去因独裁式打法被队友孤立，在与日向相遇后学会了信任队友。是日向最强的搭档和最大的对手。',
    traits:['黑发','二传手','天才','暴君','精准托球','王者','成长','日向搭档'],
    nicknames:['Tobio Kageyama','影山飞雄','Kageyama','王者'], vas:[['石川界人','']] }],
  [71267, {name:'孤爪研磨', anime_title:'排球少年', image:'https://s4.anilist.co/file/anilistcdn/character/large/b71267-q44J2MXMinXD.jpg',
    description:'音驹高中的二传手，黑尾的铁杆搭档。外表懒散对任何事都提不起劲但实际上是音驹的大脑——拥有惊人的分析能力能看穿对手的所有习惯。喜欢打游戏熬夜导致常年黑眼圈。与日向的那场宿命对决是整部作品的经典。',
    traits:['黑发','猫瞳','二传手','分析','懒散','游戏宅','黑眼圈','音驹大脑'],
    nicknames:['Kenma Kozume','孤爪研磨','Kenma','研磨'], vas:[['暂未收录','']] }],
  [74033, {name:'夜久卫辅', anime_title:'排球少年', image:'https://s4.anilist.co/file/anilistcdn/character/large/b74033-pevzERaxK8hB.png',
    description:'音驹高中的自由人，防守大师。虽然身材不高但在自由人位置上展现出了顶级实力。是研磨的定心丸和保护者。', traits:['自由人','防守','音驹','保护者'], nicknames:['Morisuke Yaku','夜久卫辅'], vas:[['暂未收录','']] }],
  [67689, {name:'清水洁子', anime_title:'排球少年', image:'https://s4.anilist.co/file/anilistcdn/character/large/b67689-QaYw1qDMjwKM.png',
    description:'乌野高中排球部的经理，黑长直眼镜美人。外表冷淡但对球队充满关心。是所有队员暗恋和尊敬的对象（虽然她本人根本不在意）。田中学长每次见到她都会过分激动。', traits:['黑发','眼镜','经理','冷淡','美人','乌野'], nicknames:['Kiyoko Shimizu','清水洁子'], vas:[['暂未收录','']] }],

  // ====== 灌篮高手 (5) ======
  [310, {name:'樱木花道', anime_title:'灌篮高手', image:'https://s4.anilist.co/file/anilistcdn/character/large/b310-3GLKM2I3EiRf.png',
    description:'湘北高中一年级，红发的篮球天才（自称）。初中时被50个女生拒绝后对篮球产生了完全的误解——为了追求晴子加入篮球部。虽然只打了四个月篮球却拥有怪物级的体格和弹跳力。每天进行"基础练习"的罚球和篮板球一步步成为真正的篮球手。名言是"因为我是天才"。',
    traits:['红发','天才自称','弹跳力','篮板王','四个月篮球经验','搞笑','热血','晴子追求者'],
    nicknames:['Hanamichi Sakuragi','樱木花道','花道','天才','篮板王'], vas:[['草尾毅','']] }],
  [311, {name:'流川枫', anime_title:'灌篮高手', image:'https://s4.anilist.co/file/anilistcdn/character/large/b311-uxwHnw9lXk4e.png',
    description:'湘北高中一年级，超级王牌选手。拥有全面的得分能力和近乎完美的篮球技术。性格极其冷淡，除了篮球和睡觉什么都不在乎。是樱木花道的头号"对手"（樱木单方面认定的）。骑车时都能睡着然后撞车的传说级睡神。',
    traits:['黑发','王牌','得分机器','冷淡','睡觉','单车睡觉撞车','樱木对手','篮球天才'],
    nicknames:['Kaede Rukawa','流川枫','Rukawa','狐狸'], vas:[['绿川光','']] }],
  [313, {name:'三井寿', anime_title:'灌篮高手', image:'https://s4.anilist.co/file/anilistcdn/character/large/b313-D720Nz8fAUxw.jpg',
    description:'湘北高中三年级，三分神射手。初中MVP因受伤放弃篮球堕落为不良少年，但在看到安西教练后哭着说出了那句经典台词——"教练，我想打篮球"。回归后成为湘北最稳定的三分火力点。体力差但意志力极强。',
    traits:['黑发','三分射手','前不良','教练我想打篮球','初中MVP','体力差','意志力','咬牙坚持'],
    nicknames:['Hisashi Mitsui','三井寿','Mitsui','炎之男'], vas:[['置鲇龙太郎','']] }],
  [314, {name:'赤木刚宪', anime_title:'灌篮高手', image:'https://s4.anilist.co/file/anilistcdn/character/large/b314-MPvsR4ndNZDd.png',
    description:'湘北高中三年级的队长，被称为"大猩猩"（但绝对不能当面叫）。197cm的身高加上铁壁般的防守是湘北内线的绝对支柱。成绩年级前五的学霸。梦想是率领湘北称霸全国。',
    traits:['黑发','197cm','大猩猩','队长','中锋','防守','学霸','称霸全国','妹妹晴子'],
    nicknames:['Takenori Akagi','赤木刚宪','Akagi','大猩猩'], vas:[['梁田清之','']] }],
  [312, {name:'宫城良田', anime_title:'灌篮高手', image:'https://s4.anilist.co/file/anilistcdn/character/large/b312-QZ0Jv451096U.png',
    description:'湘北高中二年级，电光火石般的控球后卫。168cm的身高在篮球场上完全处于劣势但他用超高速的突破弥补了一切。暗恋经理彩子，一见到她智商就归零。是球队进攻的发起点和节奏掌控者。',
    traits:['棕发','168cm','控球后卫','电光火石','暗恋彩子','速度快','突破','节奏'],
    nicknames:['Ryouta Miyagi','宫城良田','Miyagi','宫城'], vas:[['盐屋翼','']] }],

  // ====== 犬夜叉 (5) ======
  [1353, {name:'犬夜叉', anime_title:'犬夜叉', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1353-xsZhvfi7IFzT.png',
    description:'半妖少年，人类母亲与妖怪大统领之子。被封印在神木上50年后被穿越时空的少女日暮戈薇解开封印。使用父亲留下的妖刀铁碎牙战斗。性格暴躁粗鲁但内心温柔。最爱吃泡面和坐在树上发呆。',
    traits:['银发','犬耳','半妖','铁碎牙','火鼠裘','粗暴','温柔','泡面控','战国时代'],
    nicknames:['Inuyasha','犬夜叉','いぬやしゃ'], vas:[['山口胜平','']] }],
  [1354, {name:'日暮戈薇', anime_title:'犬夜叉', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1354-PuUTCSX7UzKA.png',
    description:'现代日本的初三少女，四魂之玉的转世。15岁生日那天被妖怪拉入井中穿越到战国时代。能感知四魂之玉碎片的位置，使用破魔之箭。虽然开局看似柔弱但在战斗中极其勇敢。与犬夜叉的感情线是整个故事的核心——"坐下！"',
    traits:['黑发','初三','现代人','破魔之箭','四魂之玉','穿越','勇敢','坐下命令'],
    nicknames:['Kagome Higurashi','日暮戈薇','Kagome','戈薇'], vas:[['雪野五月','']] }],
  [1355, {name:'珊瑚', anime_title:'犬夜叉', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1355-zPTmTwhMXQbt.png',
    description:'妖怪退治村的幸存者，使用飞来骨战斗。最初被奈落欺骗而向犬夜叉复仇，得知真相后成为重要伙伴。与弥勒是一对欢喜冤家。云母是她的战斗伙伴——一只可爱的双尾妖怪猫。',
    traits:['黑发','妖怪退治','飞来骨','云母','复仇','伙伴','女战士'],
    nicknames:['Sango','珊瑚','さんご'], vas:[['桑岛法子','']] }],
  [1356, {name:'弥勒', anime_title:'犬夜叉', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1356-rLhVHJzPY0Mp.jpg',
    description:'好色的法师，右手上有被奈落诅咒的风穴——会不断扩大最终吞噬他自己。平时一副不正经的样子到处要求美女"给他生孩子"但内心悲壮而温柔。使用锡杖和符咒战斗。与珊瑚的感情线是本作的又一条重要线索。',
    traits:['黑发','法师','风穴','好色','锡杖','符咒','诅咒','正经时很帅'],
    nicknames:['Miroku','弥勒','みろく'], vas:[['辻谷耕史','']] }],
  [1357, {name:'七宝', anime_title:'犬夜叉', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1357-q81pBzC7ynld.jpg',
    description:'小狐狸妖怪，犬夜叉一行人中的吉祥物担当。父亲被雷兽兄弟杀害后跟随犬夜叉一行人旅行。擅长狐狸妖术和变身术——虽然大多数时候变出来的是搞笑版本。经常因为嘲笑犬夜叉而被揍。', traits:['小狐狸','妖怪','变身术','吉祥物','搞笑担当'], nicknames:['Shippo','七宝','しっぽ'], vas:[['暂未收录','']] }],

  // ====== 精灵宝可梦 (4) ======
  [2473, {name:'小智', anime_title:'精灵宝可梦', image:'https://s4.anilist.co/file/anilistcdn/character/large/b2473-JDoo3I82Km4l.png',
    description:'来自真新镇的宝可梦训练家，永远的10岁少年。与皮卡丘是最好的搭档，梦想成为宝可梦大师。虽然每次在新地区都洗点等级归零但他对宝可梦的热爱从未改变。名言是"就决定是你了！"。20多年的旅途从未放弃。',
    traits:['黑发','10岁','训练家','永远10岁','真新镇','皮卡丘搭档','洗点','冒险','热血'],
    nicknames:['Satoshi','小智','Ash Ketchum','サトシ'], vas:[['松本梨香','']] }],
  [3891, {name:'皮卡丘', anime_title:'精灵宝可梦', image:'https://s4.anilist.co/file/anilistcdn/character/large/b3891-edgrZOgCJ9do.jpg',
    description:'小智的搭档宝可梦，电气鼠。最初完全不信任小智甚至用电击电他但后来成为全世界最亲密的人宠搭档。拒绝进化、拒绝进入精灵球。必杀技十万伏特。可爱外表背后是足以击倒传说宝可梦的实力。"Pika Pika！"',
    traits:['黄色','电气鼠','皮卡皮卡','十万伏特','不进精灵球','不进化','可爱','实力派'],
    nicknames:['Pikachu','皮卡丘','ピカチュウ','皮神'], vas:[['大谷育江','']] }],
  [125925, {name:'莉莉艾', anime_title:'精灵宝可梦', image:'https://s4.anilist.co/file/anilistcdn/character/large/b125925-CxQr9CTQbl8D.png',
    description:'阿罗拉地区的少女，以太财团的大小姐。因童年创伤无法触碰宝可梦，但在小智和同学们的帮助下逐渐克服恐惧。与UB01水母有着特殊的联系。性格温柔害羞但为了保护重要的事物会展现出惊人的勇气。',
    traits:['金发','大小姐','以太财团','宝可梦恐惧','克服','温柔','勇敢'],
    nicknames:['Lillie','莉莉艾','リーリエ'], vas:[['暂未收录','']] }],
  [126014, {name:'玛奥', anime_title:'精灵宝可梦', image:'https://s4.anilist.co/file/anilistcdn/character/large/b126014-jQuNai2bDll6.jpg',
    description:'阿罗拉地区小智的同学之一，草系宝可梦训练家。家里开餐厅，擅长制作宝可梦食物。性格开朗热情，喜欢照顾他人。与甜舞妮是亲密搭档。', traits:['绿发','草系','开朗','厨师','阿罗拉','同学'], nicknames:['Mao','玛奥'], vas:[['暂未收录','']] }],

  // ====== 魔卡少女樱 (4) ======
  [2671, {name:'木之本樱', anime_title:'魔卡少女樱', image:'https://s4.anilist.co/file/anilistcdn/character/large/2671-DflaemZz0xJo.png',
    description:'友枝小学四年级学生，被选为库洛牌的守护者。在不小心释放了库洛牌后开始了收集卡牌的旅程。使用星之杖和魔法卡牌战斗。每次变装都穿着知世亲手制作的可爱战斗服。性格善良纯真，名言是"绝对没问题！"。初代萌王的地位至今无人撼动。',
    traits:['棕发','初代萌王','库洛牌','星之杖','小学生','绝对没问题','可爱','魔法少女','知世挚友'],
    nicknames:['Sakura Kinomoto','木之本樱','小樱','Sakura','初代萌王'], vas:[['丹下樱','']] }],
  [3029, {name:'李小狼', anime_title:'魔卡少女樱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b3029-urpwynZhFdbi.jpg',
    description:'从香港来的库洛牌继承人，携带雷帝招来符进行战斗。最初与小樱是竞争库洛牌的对手，在相处中逐渐被她的善良吸引并产生了羞涩的感情。使用中国道术和宝剑。在魔法少女作品中稀有的男主角——因为他也会变身！',
    traits:['棕发','香港','库洛牌','道术','傲娇','小樱对手变恋人','雷帝招来','宝剑'],
    nicknames:['Xiaolang Li','李小狼','Syaoran','小狼'], vas:[['熊井統子','']] }],
  [3120, {name:'大道寺知世', anime_title:'魔卡少女樱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b3120-oZ4uB6NX5ReK.png',
    description:'小樱最好的朋友，超级富豪家的大小姐。最大的爱好是为小樱制作战斗服并录下她的每一场精彩战斗——为此随身携带摄像机。拥有天籁般的歌声。对小樱的爱超越了友情——她说只要小樱幸福她就足够了。',
    traits:['黑发','大小姐','摄像师','裁缝','歌唱家','小樱挚友','温柔','无私的爱'],
    nicknames:['Tomoyo Daidouji','大道寺知世','Tomoyo','知世'], vas:[['岩男润子','']] }],
  [2897, {name:'可鲁贝洛斯', anime_title:'魔卡少女樱', image:'https://s4.anilist.co/file/anilistcdn/character/large/b2897-Ckmv1Y2i9hZZ.jpg',
    description:'库洛牌的守护兽，平时是带翅膀的长毛猫玩偶形态（小可），真身是巨大的飞虎。超级爱甜食和打游戏。大阪腔的吐槽担当。虽然整天一副不靠谱的样子但在关键时刻总能保护好小樱。', traits:['金色','长毛猫','守护兽','真身飞虎','甜食','大阪腔','游戏宅','小可'], nicknames:['Cerberus','可鲁贝洛斯','小可','ケロちゃん'], vas:[['久川绫','']] }],

  // ====== 攻壳机动队 (3) ======
  [1795, {name:'草薙素子', anime_title:'攻壳机动队', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1795-vKakY5aXVyCl.jpg',
    description:'公安9课的少佐，全身义体化的最强战士。拥有超凡的战术指挥能力和格斗及黑客技能。在全身机械的外壳之下她不断追问"灵魂"的本质——一个完全义体人的人类性。赛博朋克题材中最经典的女性主角之一。',
    traits:['紫发','全身义体','少佐','公安9课','黑客','战术天才','赛博朋克','人类本质追问'],
    nicknames:['Motoko Kusanagi','草薙素子','少佐','草薙素子'], vas:[['田中敦子','']] }],
  [2653, {name:'巴特', anime_title:'攻壳机动队', image:'https://s4.anilist.co/file/anilistcdn/character/large/2653.jpg',
    description:'公安9课的义体人大汉，素子最信赖的搭档。双眼被换成义眼是他的标志。虽然外表粗犷但有着重情重义的温柔内心。战斗时使用Shotgun和各种重武器。对素子抱有超越搭档的感情。养了一只巴吉度猎犬。',
    traits:['短发','义眼','Shotgun','公安9课','素子搭档','粗犷','温柔','巴吉度猎犬'],
    nicknames:['Batou','巴特','バトー'], vas:[['大冢明夫','']] }],
  [2654, {name:'户草', anime_title:'攻壳机动队', image:'https://s4.anilist.co/file/anilistcdn/character/large/2654.jpg',
    description:'公安9课的成员，主要情报分析员和狙击手。是整个团队中家庭生活最稳定的人——有妻子和女儿。虽然是人类但在义体人包围中坚守自己的人性。使用左轮手枪。', traits:['黑发','情报分析','狙击','家庭','人类','左轮手枪'], nicknames:['Togusa','户草','トグサ'], vas:[['暂未收录','']] }],

  // ====== 心理测量者 (4) ======
  [68583, {name:'常守朱', anime_title:'心理测量者', image:'https://s4.anilist.co/file/anilistcdn/character/large/b68583-sEP2wyE2Tk7a.png',
    description:'刚毕业就被分配到公安局刑事课的年轻监视官。在西比拉系统统治的世界里监督执行官们。最初的天真理想在一次次案件中受到冲击但她没有像前辈那样黑化——而是选择从内部改变这个腐朽的系统。刑事课唯一的良心。',
    traits:['棕发','监视官','刑事课','理想主义','坚韧','不黑化','正义','西比拉系统'],
    nicknames:['Akane Tsunemori','常守朱','Akane','朱'], vas:[['花泽香菜','']] }],
  [68315, {name:'狡啮慎也', anime_title:'心理测量者', image:'https://s4.anilist.co/file/anilistcdn/character/large/b68315-f9RBjyJCoj95.jpg',
    description:'原执行官的犯罪系数超过者。曾经是最优秀的监视官，因强行追查真凶槙岛圣护而被系统降为执行官。拥有野兽般的直觉和格斗能力。与槙岛的宿命对决是整个第一部的核心。深爱白薯和咖啡。',
    traits:['黑发','执行官','野兽','复仇','槙岛宿敌','咖啡','运动万能','强袭'],
    nicknames:['Shinya Kougami','狡啮慎也','Kougami','狡啮'], vas:[['关智一','']] }],
  [69725, {name:'槙岛圣护', anime_title:'心理测量者', image:'https://s4.anilist.co/file/anilistcdn/character/large/n69725-Seck1SZfwQiR.jpg',
    description:'犯罪系数为0的完美罪犯——西比拉系统无法检测他的恶意。白发的哲学家杀手，热爱纸质书、古典音乐和被遗忘的艺术。他的目的并非简单的犯罪而是想要撬动这个被系统支配的世界。狡啮慎也一生的宿敌。',
    traits:['白发','0犯罪系数','完美罪犯','哲学家','纸质书恋','古典音乐','狡啮宿敌','优雅','冷血'],
    nicknames:['Shougo Makishima','槙岛圣护','Makishima','白毛死神'], vas:[['樱井孝宏','']] }],
  [69063, {name:'唐之杜志恩', anime_title:'心理测量者', image:'https://s4.anilist.co/file/anilistcdn/character/large/b69063-NzXNgrLJgiwr.png',
    description:'公安刑事课的分析官，负责各种数据的解析和情报支持。身材火辣但同时也是个百合倾向的女同性恋。性格洒脱不羁，与同事六合冢弥生是一对恋人。在系统监控一切的世界里保持了难得的人情味。', traits:['金发','分析官','百合','洒脱','情报','刑事课'], nicknames:['Shion Karanomori','唐之杜志恩'], vas:[['暂未收录','']] }],

  // ====== 寄生兽 (3) ======
  [12323, {name:'泉新一', anime_title:'寄生兽', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12323-NAoqDYOn2RSo.png',
    description:'普通的高中生，右手被外星寄生生物MIGI占据而保住了大脑。在与MIGI共生的过程中逐渐失去了人类的情感——泪腺、恐惧、乃至最基础的共情能力。但在面对其他寄生兽的杀戮和母亲的死亡后重新找回了"人"的本质。',
    traits:['黑发','高中生','共生','失去情感','找回人性','右手寄生','普通少年','进化'],
    nicknames:['Shinichi Izumi','泉新一','Shinichi'], vas:[['岛崎信长','']] }],
  [13773, {name:'小右', anime_title:'寄生兽', image:'https://s4.anilist.co/file/anilistcdn/character/large/b13773-Kuak0WTeTU9z.png',
    description:'寄生了泉新一右手的寄生生物。最初只是纯粹为生存而行动的冷血生物但在与新一共生过程中逐渐产生了类似人类的情感。喜欢看书获取知识。在危急时刻能变形为刀和眼等武器。对新一说——"你是我唯一的朋友"。',
    traits:['寄生生物','右手','变形武器','冷血','逐渐人性','看书','朋友'],
    nicknames:['Migi','小右','MIGI','ミギー'], vas:[['平野绫','']] }],
  [130585, {name:'草野', anime_title:'寄生兽', image:'https://s4.anilist.co/file/anilistcdn/character/large/n130585-7g7ZGqka0mOz.png',
    description:'新一的同学，温柔善良的少女。在新一变化最大的时期始终陪伴在他身边试图理解他。是故事中为数不多的人性锚点。', traits:['棕发','同学','温柔','人性锚点','理解'], nicknames:['Kusano','草野'], vas:[['暂未收录','']] }],

  // ====== 虫师 (2) ======
  [425, {name:'银古', anime_title:'虫师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b425-khK03T5n9Umq.png',
    description:'流浪的虫师，白发绿瞳的独眼男人。走遍日本各地调查与"虫"有关的神秘现象。他不消灭虫也不崇拜虫——只是作为一个观察者和平衡者让人们与虫共存。总是叼着一根烟（其实是驱虫药）。每到一个地方一个故事，治愈也是致郁。',
    traits:['白发','绿色眼瞳','独眼','虫师','流浪','观察者','治愈','驱虫烟','虫','平衡者'],
    nicknames:['Ginko','银古','ギンコ'], vas:[['中野裕斗','']] }],
  [17358, {name:'澪', anime_title:'虫师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b17358-O2jCN4Ns1cZe.png',
    description:'虫师中的一集女主角，因"眼福虫"失去了视觉却获得了看见虫的能力。银古曾教导她如何与虫共处。', traits:['黑发','失明','见虫能力','眼福虫'], nicknames:['Mio','澪'], vas:[['暂未收录','']] }],

  // ====== 三月的狮子 (4) ======
  [21044, {name:'桐山零', anime_title:'三月的狮子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b21044-K0pEhdOEmAwG.png',
    description:'17岁的职业将棋棋士，史上第五位中学生职业棋士。父母和妹妹在交通事故中去世后被父亲的朋友收养。孤独和抑郁中他只靠将棋活着——直到遇见了川本家三姐妹。她们给了他温暖的饭、吵闹的笑声和一个可以被叫做家的地方。',
    traits:['黑发','17岁','职业棋士','天才','孤独','抑郁','川本家','成长','将棋'],
    nicknames:['Rei Kiriyama','桐山零','Rei','零'], vas:[['河西健吾','']] }],
  [24311, {name:'川本明里', anime_title:'三月的狮子', image:'https://s4.anilist.co/file/anilistcdn/character/large/24311-WY1Q26PwwJeB.png',
    description:'川本家三姐妹的长女，温柔善良的代名词。因为母亲去世而早早成为了妹妹们的妈妈角色。遇到了零后总是用点心和热饭把他从孤独中拉出来。是零的太阳，也是所有读者心中的理想大姐姐。',
    traits:['黑发','长女','温柔','大姐姐','料理','照顾者','零的太阳','坚强'],
    nicknames:['Akari Kawamoto','川本明里','Akari','明里'], vas:[['茅野爱衣','']] }],
  [24312, {name:'川本日向', anime_title:'三月的狮子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b24312-A39sjFFj3Zrg.png',
    description:'川本家三姐妹的次女，活泼吵闹的元气中学生。在与零的日常拌嘴中建立了深厚的羁绊。在学校遭遇了霸凌事件却勇敢地没有退缩——零为此第一次将将棋作为武器来保护一个人。',
    traits:['棕发','次女','元气','中学生','遭受霸凌','勇敢','零的保护对象'],
    nicknames:['Hinata Kawamoto','川本日向','Hinata','日向'], vas:[['花泽香菜','']] }],
  [70295, {name:'幸田香子', anime_title:'三月的狮子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b70295-ohnNsotn2FDf.png',
    description:'零的义姐，幸田家的长女。对零有着复杂的感情——既有因零而失去父亲关注的怨恨又有无法言说的依赖。性格偏执激烈，是故事中一个令人心碎的角色。', traits:['黑发','义姐','偏执','复杂情感','怨恨','依赖'], nicknames:['Ayumu Kouda','幸田香子'], vas:[['暂未收录','']] }],

  // ====== CLANNAD (4) ======
  [4604, {name:'古河渚', anime_title:'CLANNAD', image:'https://s4.anilist.co/file/anilistcdn/character/large/b4604-YFJiWeuGSIYf.png',
    description:'因长期生病而留级的温柔少女。在樱花坡道的坡道上——"你喜欢这所学校吗？我非常非常喜欢。但这一切都在改变。"朋也因为这不可思议的相遇踏上了改变人生的旅程。最爱团子大家族，梦想是在演剧部重新登台。AS篇的结局至今让无数人泪崩。',
    traits:['棕发','体弱','留级','温柔','团子大家族','演剧部','樱花坡道','坚强','母亲'],
    nicknames:['Nagisa Furukawa','古河渚','Nagisa','渚'], vas:[['中原麻衣','']] }],
  [4606, {name:'冈崎朋也', anime_title:'CLANNAD', image:'https://s4.anilist.co/file/anilistcdn/character/large/b4606-61r9h3WUrkA9.png',
    description:'因为受伤失去篮球梦想的不良少年，与父亲关系彻底破裂过着自暴自弃的生活——直到遇到了古河渚。在与渚的交往中从少年成长为男人再成长为父亲。他的故事是关于废柴如何被一个温柔的女孩子拯救，又是如何拯救自己的孩子。',
    traits:['蓝发','不良少年','父亲','成长','自暴自弃','被拯救','拯救女儿'],
    nicknames:['Tomoya Okazaki','冈崎朋也','Tomoya','朋也'], vas:[['中村悠一','']] }],
  [4602, {name:'一之濑琴美', anime_title:'CLANNAD', image:'https://s4.anilist.co/file/anilistcdn/character/large/b4602-L9sSmkyQhZeC.jpg',
    description:'天才少女，总是独自在图书室看书。父母是著名学者但在空难中去世，留给她唯一的遗物是一只破旧的熊玩偶和一整箱的论文。朋也和渚帮她找到了父母的"遗言"——写在每篇论文扉页上的对女儿的爱。',
    traits:['黑发','长发','天才','图书室','孤独','小提琴','熊玩偶','父母空难'],
    nicknames:['Kotomi Ichinose','一之濑琴美','Kotomi','琴美'], vas:[['能登麻美子','']] }],
  [4601, {name:'伊吹风子', anime_title:'CLANNAD', image:'https://s4.anilist.co/file/anilistcdn/character/large/b4601-ndvzx7vVREJU.jpg',
    description:'用木雕海星送给全校学生的少女——为了让大家参加姐姐的婚礼。但有一个问题：真正的风子正躺在医院的病床上昏迷不醒，而校园里这个不停雕刻海星的她其实只是思念化作的存在。海星的故事是CLANNAD第一滴泪。',
    traits:['棕发','海星雕刻','昏迷','幽灵体','姐姐的婚礼','可爱','执着'],
    nicknames:['Fuuko Ibuki','伊吹风子','Fuuko','风子'], vas:[['野中蓝','']] }],

  // ====== EVA 新世纪福音战士 (5) ======
  [89, {name:'碇真嗣', anime_title:'新世纪福音战士', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89-ZtZhXkh1rITn.png',
    description:'14岁的EVA初号机驾驶员，被父亲碇源堂抛弃多年后突然被叫来驾驶巨大的机器人战斗。极度内向自卑，渴望得到父亲的认可和别人的需要。每次驾驶EVA都会受伤但总是回来——因为他害怕不被需要的孤独比死亡更可怕。史上最经典的"废柴主角"。',
    traits:['棕发','14岁','EVA驾驶员','内向','自卑','渴望认可','S-DAT','大提琴','废柴主角'],
    nicknames:['Shinji Ikari','碇真嗣','Shinji','真嗣'], vas:[['绪方惠美','']] }],
  [86, {name:'绫波丽', anime_title:'新世纪福音战士', image:'https://s4.anilist.co/file/anilistcdn/character/large/86-cA1zL7fyls8E.jpg',
    description:'EVA零号机的驾驶员，三无少女的元祖。蓝发红瞳的她几乎没有表情和情感——她是被制造出来的人造人，有无数个备用的自己。但在与真嗣的相处中她第一次产生了"想保护某个人"的念头。她的微笑是整个EVA中最珍贵的瞬间。',
    traits:['蓝发','红色眼瞳','三无','人造人','EVA驾驶员','绫波系列','微笑','牺牲'],
    nicknames:['Rei Ayanami','绫波丽','Rei','綾波レイ','女神'], vas:[['林原惠美','']] }],
  [94, {name:'惣流·明日香·兰格雷', anime_title:'新世纪福音战士', image:'https://s4.anilist.co/file/anilistcdn/character/large/b94-d631a3Z2KPvd.png',
    description:'EVA二号机驾驶员，德日混血的天才少女。外表高傲自信但内心极度脆弱——母亲的发疯和自杀是她最深的创伤。通过成为最优秀的驾驶员来证明自己的存在价值。她的崩溃是整部作品中最令人心碎的部分之一。口头禅是"你笨蛋啊？"。',
    traits:['红发','混血','天才少女','傲娇','EVA驾驶员','童年创伤','骄傲','崩溃','名校毕业'],
    nicknames:['Asuka Langley Souryuu','明日香','Asuka','アスカ'], vas:[['宫村优子','']] }],
  [1259, {name:'葛城美里', anime_title:'新世纪福音战士', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1259-afTQkZ5SVMOn.png',
    description:'NERV的作战部长，EVA驾驶员们的监护人。在同事面前是干练的指挥官，在家里是冰箱装满啤酒的废柴御姐。用豪放的生活方式和大吃大喝来掩盖童年的创伤——她是第二次冲击中唯一的幸存者。是真嗣亦母亦姐的存在。',
    traits:['紫发','NERV','作战部长','啤酒','企鹅PenPen','御姐','童年创伤','真嗣监护人'],
    nicknames:['Misato Katsuragi','葛城美里','Misato','美里'], vas:[['三石琴乃','']] }],
  [1262, {name:'铃原东治', anime_title:'新世纪福音战士', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1262-srj1373Rz8dI.png',
    description:'真嗣的同学和好友，运动少年。最初因为妹妹在EVA战斗中受伤而暴打真嗣，后来成为真嗣在学校最好的朋友。EVA三号机驾驶员（那一集……不说了）。性格直率阳光，是真嗣稀有的正常人朋友。', traits:['棕发','运动员','真嗣好友','直率','EVA三号机','悲剧'], nicknames:['Touji Suzuhara','铃原东治'], vas:[['暂未收录','']] }],

  // ====== 你的名字 (2) ======
  [121514, {name:'宫水三叶', anime_title:'你的名字。', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121514-MGI7JRluscpz.png',
    description:'生活在岐阜县飞驒深山里为神社巫女仪式而烦恼的高中女生。某天突然与东京的男高中生立花泷开始不定期交换身体。这段跨越时空的奇幻经历最终引向了一个关于记忆、彗星和重逢的动人故事。那条红色发带是她与泷之间超越时间的羁绊。',
    traits:['黑发','巫女','高中生','口嚼酒','发带','彗星','交换身体','穿越时空'],
    nicknames:['Mitsuha Miyamizu','宫水三叶','Mitsuha','三叶'], vas:[['上白石萌音','']] }],
  [121516, {name:'立花泷', anime_title:'你的名字。', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121516-kuPVJLNsH5uE.png',
    description:'生活在东京的高中男生，喜欢建筑和素描。某天开始与深山町的少女三叶不定期交换身体。这种奇异体验从互相恶作剧开始逐渐变为挂念和寻找。最终发现两人之间不仅隔着空间——还隔着整整三年时间和一场毁灭性的灾难。她的名字，他绝对不要忘记。',
    traits:['棕发','高中生','建筑','素描','交换身体','穿越时空','寻找三叶','你的名字'],
    nicknames:['Taki Tachibana','立花泷','Taki','泷'], vas:[['神木隆之介','']] }],

  // ====== 天气之子 (3) ======
  [139710, {name:'天野阳菜', anime_title:'天气之子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b139710-EnN2wXd5YeDb.png',
    description:'能用祈祷让天空放晴的少女——"100%的晴女"。与弟弟相依为命住在东京。每次使用祈晴能力她的身体就会逐渐变透明——因为她正在被天空吞噬。当帆高问她"你想要回去吗"时她选择了和他一起留在地上——"比起蓝天，我选择你。',
    traits:['黑发','晴女','祈晴','透明化','照顾弟弟','比蓝天更重要的选择'],
    nicknames:['Hina Amano','天野阳菜','Hina','阳菜','晴女'], vas:[['森七菜','']] }],
  [139709, {name:'森岛帆高', anime_title:'天气之子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b139709-LipsW9CYvlu1.png',
    description:'离家出走来到东京的16岁少年。独自在池袋的网吧和街头流浪时遇到了改变天气的少女阳菜。为了守护她愿意与整个东京的天气为敌。他的爱是自私的却是纯粹的——哪怕让整个东京沉入雨中也在所不惜。',
    traits:['黑发','离家出走','16岁','为爱自私','不后悔','守护阳菜'],
    nicknames:['Hodaka Morishima','森岛帆高','Hodaka','帆高'], vas:[['醍醐虎汰朗','']] }],
  [139703, {name:'天野凪', anime_title:'天气之子', image:'https://s4.anilist.co/file/anilistcdn/character/large/b139703-A9GVtE2EscpF.png',
    description:'阳菜的弟弟，一个早熟懂事的小学男生。在姐姐为生计奔波时陪在她身边，也在帆高最困难的时候给予了帮助。是这部作品中可爱又让人心疼的弟弟角色。', traits:['棕发','小学生','弟弟','早熟','懂事'], nicknames:['Nagi Amano','天野凪'], vas:[['暂未收录','']] }],

  // ====== 秒速五厘米 (3) ======
  [1810, {name:'远野贵树', anime_title:'秒速五厘米', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1810-mqwzwrC5XnOW.png',
    description:'从小不断转学的少年，在樱花飘落的季节与明里相遇。在漫长的铁路旁——"知道吗？樱花飘落的速度是每秒五厘米。"跨越小学、中学和成人后的三段人生，他与明里的距离从一封信变成了再也回不去的铁路道口。这个故事关于时间、距离和终究无法抵达的爱。',
    traits:['黑发','转学生','樱花','写信','时间','距离','无法抵达','铁路'],
    nicknames:['Takaki Tohno','远野贵树','Takaki'], vas:[['水桥研二','']] }],
  [1811, {name:'篠原明里', anime_title:'秒速五厘米', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1811-6uPM6WpVt20k.png',
    description:'贵树小学时的转学生——两个总是转学的孩子在樱花季节相遇。一起看过的樱花、一起走过的雪夜铁路、还有那封从她手中飞走始终没给出去的信。13年后，在铁路道口擦肩而过的两人与樱花一起成为永恒的记忆。',
    traits:['黑发','转学生','樱花','信','错过','13年','铁路道口'],
    nicknames:['Akari Shinohara','篠原明里','Akari','明里'], vas:[['近藤好美','']] }],
  [1812, {name:'澄田花苗', anime_title:'秒速五厘米', image:'https://s4.anilist.co/file/anilistcdn/character/large/1812.jpg',
    description:'贵树在种子岛高中时的同学，暗恋他的冲浪少女。她总是陪在贵树身边却始终没有勇气表白——因为她知道他的心不在她这里。学会冲浪的过程也是学会放下的过程。', traits:['棕发','冲浪','暗恋','不敢表白','放下'], nicknames:['Kanae Sumida','澄田花苗'], vas:[['暂未收录','']] }],

  // ====== 千与千寻 (4) ======
  [384, {name:'荻野千寻', anime_title:'千与千寻', image:'https://s4.anilist.co/file/anilistcdn/character/large/b384-AoWCsQyG0WI7.png',
    description:'10岁的普通少女，在搬家的路上误入神灵世界——汤屋。父母因贪吃变成了猪，她必须在汤婆婆的支配下工作才能救回父母。从胆小的爱哭鬼一步步成长为能够拯救所有人的坚强女孩。白龙告诉她——"千万不要忘记自己的名字"。宫崎骏最经典的作品主角。',
    traits:['棕发','10岁','汤屋','名字','成长','勇敢','白龙','父母变猪','神隐'],
    nicknames:['Chihiro Ogino','荻野千寻','Chihiro','千','千寻'], vas:[['柊瑠美','']] }],
  [385, {name:'赈早见琥珀主', anime_title:'千与千寻', image:'https://s4.anilist.co/file/anilistcdn/character/large/b385-pKGCy3oYWxRa.png',
    description:'汤屋中的白龙——汤婆婆的弟子。温柔地引导迷失在神灵世界的千寻，帮助她生存下来。他的真实身份是琥珀川的河神，千寻小时候曾掉进他的河里被他救过。在千寻的帮助下终于想起了自己真正的名字——赈早见琥珀主。',
    traits:['白发','白龙','河神','汤婆婆弟子','温柔','名字被夺','琥珀川','龙形态'],
    nicknames:['Haku','白龙','赈早见琥珀主','ハク'], vas:[['入野自由','']] }],
  [4716, {name:'汤婆婆', anime_title:'千与千寻', image:'https://s4.anilist.co/file/anilistcdn/character/large/b4716-8uiG2k2QxKvN.png',
    description:'汤屋的主人——统治着整个神灵澡堂世界的魔女。体型巨大长相恐怖的婆婆，通过夺走名字来控制手下的工人。虽然冷酷贪婪但对她的巨型婴儿却是百般宠爱。有着让人印象深刻的鹰钩鼻和巨大的头。', traits:['魔女','汤屋','夺名','贪婪','巨型婴儿','鹰钩鼻','统治者','恐怖'], nicknames:['Yubaba','汤婆婆','ゆばーば'], vas:[['暂未收录','']] }],
  [8301, {name:'釜爷', anime_title:'千与千寻', image:'https://s4.anilist.co/file/anilistcdn/character/large/b8301-ASa313sbbcI3.png',
    description:'汤屋锅炉房的管理者，六只蜘蛛般的手臂同时操控无数抽屉。外表恐怖但内心温柔的老人，是汤屋中第一个真正帮助千寻的人。给千寻工作并默默守护着她。', traits:['六臂','锅炉房','蜘蛛','老者','温柔','守护千寻'], nicknames:['Kamajii','釜爷','釜じい'], vas:[['暂未收录','']] }],

  // ====== 黑子的篮球 (4) ======
  [18769, {name:'黑子哲也', anime_title:'黑子的篮球', image:'https://s4.anilist.co/file/anilistcdn/character/large/b18769-1SOeKdgkjBef.png',
    description:'帝光中学"奇迹的世代"的幻之第六人——因为存在感极低而在球场上几乎不可见。他的传球利用低存在感的特性将球传到无人预判到的位置。高中加入了新建的诚凛高中篮球队并与火神大我搭档，目标是打败所有奇迹世代的旧队友。外号"影子"。',
    traits:['蓝发','存在感低','影子','传球','帝光中学','奇迹世代','第六人','香草奶昔'],
    nicknames:['Tetsuya Kuroko','黑子哲也','Kuroko','黑子'], vas:[['小野贤章','']] }],
  [18770, {name:'火神大我', anime_title:'黑子的篮球', image:'https://s4.anilist.co/file/anilistcdn/character/large/b18770-iLAk9O3GGUvN.png',
    description:'从美国归来的超级新人，拥有压倒性的身体素质——超强跳跃力和力量。与黑子组成光与影的二人组合。诚凛高中的王牌。目标是成为日本第一——和黑子一起打败奇迹的世代。比赛中会进入"Zone"状态。吃货，最爱汉堡。',
    traits:['红发','归国子女','跳跃力','Zone','王牌','吃货','汉堡','黑子之光'],
    nicknames:['Taiga Kagami','火神大我','Kagami','火神'], vas:[['小野友树','']] }],
  [36976, {name:'紫原敦', anime_title:'黑子的篮球', image:'https://s4.anilist.co/file/anilistcdn/character/large/b36976-fVmQY9GqvHHa.png',
    description:'奇迹世代的中锋，208cm的巨人。拥有一手就能握住篮球的巨掌，防守范围覆盖整个三分线内。平时懒洋洋说话有气无力，但只要被惹怒就会展现恐怖的实力。爱吃零食，比赛时都要叼着零食棒。', traits:['紫发','208cm','中锋','奇迹世代','贪吃','懒散','零食棒','防守范围极大'], nicknames:['Atsushi Murasakibara','紫原敦','Murasakibara'], vas:[['铃村健一','']] }],
  [53563, {name:'高尾和成', anime_title:'黑子的篮球', image:'https://s4.anilist.co/file/anilistcdn/character/large/b53563-6ZzDEnRCQQTR.jpg',
    description:'秀德高中的控球后卫，绿间真太郎的搭档和"鹰之眼"拥有者。能一眼看穿全场所有人位置的视野。骑一辆奇特的板车——后面坐着绿间。性格开朗随和，是绿间唯一的好朋友。', traits:['黑发','控球后卫','鹰之眼','板车','开朗','绿间搭档'], nicknames:['Kazunari Takao','高尾和成'], vas:[['暂未收录','']] }],

  // ====== 星际牛仔 (4) ======
  [1, {name:'史派克·斯皮格尔', anime_title:'星际牛仔', image:'https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png',
    description:'Bebop号上的赏金猎人，李小龙般的截拳道高手。过去是火星犯罪组织"红龙"的成员，在一次背叛中假死脱身。绿色蓬松发型的太空牛仔。随身携带一包香烟。总是潇洒随意地解决事件然后大喊——"没有肉丝的青椒肉丝还叫什么青椒肉丝！"。他的故事始于一场梦也终于一场梦。See you space cowboy。',
    traits:['绿发','赏金猎人','截拳道','太空牛仔','Bebop','香烟','红龙过去','悲剧','SeeYouSpaceCowboy'],
    nicknames:['Spike Spiegel','史派克','Spike','太空牛仔'], vas:[['山寺宏一','']] }],
  [3, {name:'杰特·布莱克', anime_title:'星际牛仔', image:'https://s4.anilist.co/file/anilistcdn/character/large/b3-JjH9Si9UM1NZ.png',
    description:'Bebop号的船长，前ISSP警官。机械手臂是他被背叛的证明。喜欢盆栽和爵士乐。是整个Bebop团队中最可靠的成年人——但也是最被史派克坑的队友。擅长做一种叫"贝尔辣椒与牛肉没有牛肉"的料理。',
    traits:['光头','机械臂','前警察','盆栽','爵士','船长','成年人','做饭难吃'],
    nicknames:['Jet Black','杰特','Jet','ジェット'], vas:[['石冢运升','']] }],
  [2, {name:'菲·瓦伦丁', anime_title:'星际牛仔', image:'https://s4.anilist.co/file/anilistcdn/character/large/b2-0Iszg6Izgt4p.png',
    description:'Bebop号上的女赏金猎人，失忆的冷冻睡眠者。实际年龄超过70岁但外表是20多岁的性感美女。擅长赌博和骗术，欠了一屁股债。被冷冻睡眠多年醒来后失去了所有记忆——为了寻找自己的过去而不断流浪。对史派克若即若离却离不开Bebop的伙伴们。',
    traits:['紫发','赏金猎人','失忆','冷冻睡眠','70岁外表','赌博','欠债','性感'],
    nicknames:['Faye Valentine','菲·瓦伦丁','Faye','フェイ'], vas:[['林原惠美','']] }],
  [16, {name:'艾德', anime_title:'星际牛仔', image:'https://s4.anilist.co/file/anilistcdn/character/large/b16-80wd87nl1Rue.png',
    description:'Bebop号的天才黑客少女——全名爱德华·王·侯·比勃·提布鲁斯基四世。13岁的超级黑客用一台旧电脑就能黑入任何系统。性格天真古怪，整天赤脚跑来跑去。带着一只数据狗Ein。最后在Bebop甲板上画了个笑脸后潇洒离开。',
    traits:['红发','天才黑客','13岁','赤脚','数据狗','天真','古怪','笑脸','再见'],
    nicknames:['Edward Wong Hau Pepelu Tivrusky IV','艾德','Ed','爱德华'], vas:[['多田葵','']] }],
]

let count = 0
for (const [id, d] of data) {
  const { error } = await supabase.from('characters').upsert({
    id, name: d.name, anime_title: d.anime_title, image: d.image,
    description: d.description, traits: d.traits, nicknames: d.nicknames,
  }, { onConflict: 'id' })
  if (d.vas) {
    await supabase.from('voice_actors').delete().eq('character_id', id)
    for (const [name, img] of d.vas) {
      await supabase.from('voice_actors').insert({ character_id: id, name, image: img || '', language: '日语' })
    }
  }
  process.stdout.write(error ? '❌' : '+')
  count++
}
console.log('\n重建 search_text...')
const { data: chars } = await supabase.from('characters').select('id, name, anime_title, nicknames, traits, voice_actors(name)')
for (const c of chars||[]) {
  const st = [c.name, c.anime_title||'', ...(c.nicknames||[]), ...(c.traits||[]), ...(c.voice_actors||[]).map(v=>v.name)].join(' ')
  await supabase.from('characters').update({ search_text: st }).eq('id', c.id)
}
console.log('✅', count, '个角色')
