import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY)

const data = [
  // ====== 刀剑神域 (6) ======
  [36765, { name:'桐谷和人', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png',
    description:'刀剑神域的主角，游戏昵称"桐人"。在死亡游戏SAO中以独行玩家身份闯关，被称为"黑色剑士"。拥有超群的战斗天赋和反应速度，是SAO通关的关键人物。现实中是重度网游玩家，性格冷静但为保护重要的人不惜一切。拥有双刀流技能。',
    traits:['黑发','黑色眼瞳','黑色剑士','独行玩家','双刀流','网游废人','冷静','战斗天才','SAO通关者','VRMMO'],
    nicknames:['Kazuto Kirigaya','桐谷和人','桐人','Kirito','黑色剑士'],
    vas:[['松冈祯丞','']] }],
  [36828, { name:'结城明日奈', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png',
    description:'SAO中昵称"亚丝娜"，被称为"闪光"。公會血盟骑士团的副团长，使用细剑的顶尖玩家。现实中是名门大小姐，在SAO中展现了坚强的意志和卓越的战斗力。与桐人从并肩作战发展为恋人关系，是系列中最具人气的女性角色。',
    traits:['棕发','长发','闪光','细剑使','副团长','血盟骑士团','大小姐','料理达人','战斗力极强','SAO攻略组'],
    nicknames:['Asuna Yuuki','结城明日奈','亚丝娜','Asuna','闪光'],
    vas:[['户松遥','']] }],
  [36831, { name:'桐谷直叶', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b36831-JfyFU7gPPVmr.png',
    description:'桐人的妹妹，并非亲生。在现实世界中是剑道部主将，在ALO中以"莉法"之名使用风精灵角色。对哥哥一直抱有情愫。性格坚强努力，在ALO中拥有出色的飞行技巧和战斗力。',
    traits:['黑发','短发','剑道','莉法','风精灵','ALO','兄控','坚强','运动少女'],
    nicknames:['Suguha Kirigaya','桐谷直叶','莉法','Leafa','直叶'],
    vas:[['竹达彩奈','']] }],
  [55147, { name:'朝田诗乃', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b55147-1fCU8lONEuZQ.png',
    description:'GGO中的超一流狙击手，游戏昵称"诗音"。现实中因童年枪击事件留下心理创伤，在游戏中克服恐惧。使用PGM Ultima Ratio Hecate II反器材步枪。性格冷静沉稳，与桐人建立了深厚的信任关系。',
    traits:['黑发','短发','眼镜娘','狙击手','反器材步枪','诗音','GGO','冷静','PTSD','实力派'],
    nicknames:['Shino Asada','朝田诗乃','诗音','Sinon','Hecate狙击手'],
    vas:[['泽城美雪','']] }],
  [72903, { name:'尤金', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b72903-sydZD4sXrDTw.png',
    description:'ALO中火精灵族的将军，全种族最强玩家之一。使用传说级武器魔剑格拉姆，在ALO中拥有极高的声望和战斗力。外表粗犷但重情重义，在战斗和谈判中展现了领袖风范。',
    traits:['赤发','将军','火精灵','魔剑格拉姆','最强玩家','ALO','领袖','重情义','粗犷'],
    nicknames:['Eugene','尤金','火精灵将军'],
    vas:[['三宅健太','']] }],
  [36830, { name:'克莱因', anime_title:'刀剑神域', image:'https://s4.anilist.co/file/anilistcdn/character/large/b36830-41SWIDvhqOo4.png',
    description:'SAO中的太刀使，风林火山公会的会长。是桐人在SAO中最早结识的朋友和好大哥。性格豪爽热情，使用一把大型武士刀战斗。虽不是顶尖玩家但领导力和人格魅力极强。在现实世界也是桐人最好的朋友之一。',
    traits:['红棕发','太刀使','风林火山','公会会长','豪爽','好大哥','武士刀','可靠','朋友'],
    nicknames:['Ryoutarou Tsuboi','克莱因','Klein','风林火山会长'],
    vas:[['平田广明','']] }],

  // ====== 钢之炼金术师 (7) ======
  [11, { name:'爱德华·艾尔利克', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg',
    description:'史上最年轻的国家炼金术师，被称为"钢之炼金术师"。12岁时与弟弟阿尔想要复活死去的母亲而进行了人体炼成，代价是失去左腿和右手。矮个子是他最在意的事（谁提跟谁急）。性格倔强但正义感极强，踏上寻找贤者之石的旅程。',
    traits:['金发','金色眼瞳','矮个子','国家炼金术师','机械铠','倔强','正义','天才','弟控','豆丁','人体炼成禁忌'],
    nicknames:['Edward Elric','爱德华·艾尔利克','爱德','钢之炼金术师','Fullmetal','豆丁'],
    vas:[['朴璐美','']] }],
  [12, { name:'阿尔冯斯·艾尔利克', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b12-tCKu8yK5kFL5.jpg',
    description:'爱德华的弟弟，在人体炼成失败后失去了整个身体，灵魂被固定在一副巨大盔甲中。性格温柔善良，虽然外表恐怖内心却比任何人都温柔。擅长格斗术，盔甲身躯让他百毒不侵。与哥哥共同寻找恢复身体的方法。',
    traits:['无身体','盔甲','温柔','善良','格斗术','灵魂固定','爱猫','钢铁之躯','恢复身体','弟弟'],
    nicknames:['Alphonse Elric','阿尔冯斯·艾尔利克','阿尔','Al','盔甲弟弟'],
    vas:[['钉宫理惠','']] }],
  [68, { name:'罗伊·马斯坦古', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png',
    description:'国家炼金术师，被称为"焰之炼金术师"。使用带有炼成阵的特制手套制造火焰。东方司令部所属，梦想成为大总统来改善这个国家。外表玩世不恭但极有野心和正义感。下雨天战斗力归零，人称"雨无能"。',
    traits:['黑发','焰之炼金术师','火焰','手套','大总统梦想','野心','正义','雨无能','玩世不恭','东方司令部'],
    nicknames:['Roy Mustang','罗伊·马斯坦古','Mustang','焰之炼金术师','大佐','无能大佐'],
    vas:[['三木真一郎','']] }],
  [70, { name:'莉莎·霍克艾', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b70-k4bCgDspyOdI.png',
    description:'马斯坦古的副官和贴身护卫，被称为鹰眼。枪法精准无比，百发百中。马斯坦古称她为"我的女王"。性格冷静忠诚，始终守护着马斯坦古的背后——因为"他背后有我看不到的弱点"。',
    traits:['金发','短发','鹰眼','神枪手','副官','冷静','忠诚','狙击','马斯坦古背后'],
    nicknames:['Riza Hawkeye','莉莎·霍克艾','霍克艾','鹰眼','中尉'],
    vas:[['根谷美智子','']] }],
  [63, { name:'温莉·洛克贝尔', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/63-xloedtYxiJ2E.jpg',
    description:'爱德华和阿尔冯斯的青梅竹马，天才机械铠技师。从祖母那里继承了机械铠修理技术，负责维护爱德华的机械铠。性格开朗坚强，对爱德和阿尔有着深厚的感情。生气时用扳手打人毫不手软。',
    traits:['金发','机械铠技师','青梅竹马','扳手','开朗','坚强','天才女技师','医务者'],
    nicknames:['Winry Rockbell','温莉·洛克贝尔','Winry','机械铠天才'],
    vas:[['高本惠','']] }],
  [9792, { name:'冯·霍恩海姆', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b9792-YA8kiO4NjmGL.jpg',
    description:'爱德华和阿尔冯斯的父亲，拥有不死之身的贤者之石本体（活体贤者之石）。数百年前与烧瓶中的小人做了交易，获得了永生却付出了无法老去的代价。外表年轻但实际年龄超过400岁。',
    traits:['金发','贤者之石','不死之身','400岁','父亲','活体贤者之石','高深莫测','眼镜','悲剧'],
    nicknames:['Van Hohenheim','霍恩海姆','父亲大人','活体贤者之石'],
    vas:[['石冢运升','']] }],
  [5988, { name:'罗赛·托马斯', anime_title:'钢之炼金术师', image:'https://s4.anilist.co/file/anilistcdn/character/large/b5988-Wo1TMSnDnPIm.jpg',
    description:'里欧尔事件中遇到的少女，坚信太阳神教能复活死去的恋人。被骗后被爱德华教训了一顿（人造人伪装的教主）。后来跟随马尔科医生四处救助受贤者之石之害的人们，成长为坚强独立的女性。',
    traits:['棕发','少女','里欧尔','太阳神教','被骗','成长','坚强','独立'],
    nicknames:['Rosé Tomas','罗赛','Rose'],
    vas:[['桑岛法子','']] }],

  // ====== Re:从零开始 (7) ======
  [88573, { name:'菜月昴', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png',
    description:'从便利店出来突然被召唤到异世界的高中生。唯一的能力是"死亡回归"——死后能以一定存档点复活。性格乐观但极度自虐，在反复的死亡中承受着常人无法想象的痛苦。深爱着艾米莉亚，为了拯救所有人不惜一次次赴死。',
    traits:['黑发','运动服','高中生','NEET','死亡回归','自虐','乐观','艾米莉亚厨','异世界','精神承伤','怠惰权能'],
    nicknames:['Subaru Natsuki','菜月昴','昴','Subaru','486'],
    vas:[['小林裕介','']] }],
  [88572, { name:'艾米莉亚', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88572-IzTwXEHSobRs.jpg',
    description:'卢格尼卡王国的半妖精少女，王选候选人之一。银发紫瞳的美少女，因外貌酷似嫉妒魔女而被世人歧视。性格善良单纯，使用冰系魔法和精灵术。虽然被昴深爱却经常对他的过度保护感到困惑。',
    traits:['银发','紫瞳','半妖精','王选候选人','冰系魔法','精灵使','善良','单纯','被歧视','嫉妒魔女长相'],
    nicknames:['Emilia','艾米莉亚','EMT','艾米莉亚碳','精灵术士'],
    vas:[['高桥李依','']] }],
  [88575, { name:'蕾姆', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png',
    description:'罗兹瓦尔宅邸的双子女仆之一，拉姆的妹妹。蓝发鬼族少女，使用流星锤战斗。曾经因过去的愧疚而极度自卑，但被昴拯救后成为他最坚定的支持者。名言是"昴是蕾姆的英雄"。料理和家务全能。',
    traits:['蓝发','短发','鬼族','女仆','流星锤','自卑','温柔','昴的支柱','全能','姐控','毒舌'],
    nicknames:['Rem','蕾姆','雷姆','蓝色女仆','鬼族少女'],
    vas:[['水濑祈','']] }],
  [88576, { name:'拉姆', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88576-NWkotUiJ3mK3.png',
    description:'罗兹瓦尔宅邸的双子女仆之一，蕾姆的姐姐。粉发鬼族，曾是最强的鬼族但因角被折断而魔力大减。性格傲娇毒舌，从不放过任何挖苦昴的机会但内心十分关心妹妹。与罗兹瓦尔有着复杂的关系。',
    traits:['粉发','短发','鬼族','女仆','傲娇','毒舌','姐控','角断','原最强','风魔法'],
    nicknames:['Ram','拉姆','粉色女仆','鬼族姐姐'],
    vas:[['村川梨衣','']] }],
  [90181, { name:'碧翠丝', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b90181-wRPm0OEaucmw.png',
    description:'罗兹瓦尔宅邸禁书库的守护者，外表是可爱的双卷发幼女但实际是400岁的人造精灵。口头禅是"真是的"（やれやれ）。性格傲娇，拥有强大的空间转移魔法。在禁书库孤独等待了400年的"那个人"。',
    traits:['金发','双卷发','幼女外表','400岁','精灵','禁书库','空间魔法','傲娇','等待400年','碧翠丝'],
    nicknames:['Beatrice','碧翠丝','贝蒂','Beako','禁书库司书'],
    vas:[['新井里美','']] }],
  [90178, { name:'阿尔迪巴兰', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b90178-olaN8k9RJRxo.png',
    description:'普莉希拉的骑士，全身盔甲只露出头盔下的两只眼睛。来自与昴相同的世界（日本），时间上比昴早了约18年。战斗经验丰富，与昴一起对抗过魔女教。真实身份和目的笼罩在谜团之中。',
    traits:['盔甲','骑士','穿越者','18年前','战斗老练','谜团','忠心','阳光系'],
    nicknames:['Aldebaran','阿尔迪巴兰','Al','Aldebaran','头盔骑士'],
    vas:[['藤原启治','']] }],
  [185046, { name:'拉塞尔·费罗', anime_title:'Re:从零开始的异世界生活', image:'https://s4.anilist.co/file/anilistcdn/character/large/b185046-chJWaKEwVlZs.jpg',
    description:'商业都市普利斯特拉的富商之子，为人狡猾精明的商人。在王选篇中与昴打过交道，展现了卢格尼卡经济圈商人们的复杂生态。',
    traits:['商人','精明','富家子弟','普利斯特拉','谈判','经济'],
    nicknames:['Russell Fellow','拉塞尔·费罗','Russell'],
    vas:[['暂未收录','']] }],

  // ====== 一拳超人 (5) ======
  [73935, { name:'埼玉', anime_title:'一拳超人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg',
    description:'兴趣使然的英雄，称号"秃头披风侠"。经过三年每天100个俯卧撑+100个仰卧起坐+100个深蹲+10km长跑后获得了无敌的力量，任何敌人都能一拳解决。但因为太强而陷入了深深的空虚和无聊。平时最大的烦恼是超市打折和不断变秃。',
    traits:['光头','披风','一拳必杀','无敌','空虚','超市打折','C级英雄','锻炼狂','最强','黄色战服','表情简单','兴趣使然'],
    nicknames:['Saitama','埼玉','秃头披风侠','一拳超人','老师'],
    vas:[['古川慎','']] }],
  [73979, { name:'杰诺斯', anime_title:'一拳超人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b73979-tVi9maPID881.jpg',
    description:'S级第14位的改造人英雄，称号"魔鬼改造人"。全家被暴走改造人杀害后被库赛诺博士所救。为了变得更强而拜埼玉为师，忠实地做笔记记录老师的教导。虽然实力强大但总是在关键时刻被击毁等待升级。',
    traits:['金发','改造人','S级英雄','埼玉徒弟','笔记者','酷帅','复仇','机械','不断升级','燃尽'],
    nicknames:['Genos','杰诺斯','魔鬼改造人','Genos','徒弟君'],
    vas:[['石川界人','']] }],
  [81929, { name:'战栗的龙卷', anime_title:'一拳超人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b81929-WPVp2LQoWgkc.png',
    description:'S级第2位的超能力者，称号"战栗的龙卷"。虽然外表是幼女但实际年龄28岁。拥有极其强大的念动力，可以轻松拉动陨石和撕碎龙级怪人。性格高傲任性，极度厌恶被当成小孩子看待。',
    traits:['绿发','幼女外表','28岁','超能力者','S级No.2','念动力','傲娇','暴躁','龙卷','最强超能力者'],
    nicknames:['Tatsumaki','战栗的龙卷','龙卷','龍卷'],
    vas:[['悠木碧','']] }],
  [89277, { name:'饿狼', anime_title:'一拳超人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b89277-xBGb4B5YISXg.png',
    description:'原邦古的弟子，被英雄协会视为S级威胁的人类怪人。小时候总是被迫扮演被英雄打倒的怪人角色而形成了对英雄的逆反心理。拥有超强的武术天赋和"英雄狩猎"的称号，最终几乎完全怪人化。',
    traits:['灰发','武术','英雄狩猎','怪人','人类怪人','格斗天才','逆反','中二','曾被霸凌','已超越极限'],
    nicknames:['Garou','饿狼','Garou','英雄猎人'],
    vas:[['绿川光','']] }],
  [86031, { name:'超合金黑光', anime_title:'一拳超人', image:'https://s4.anilist.co/file/anilistcdn/character/large/b86031-7NpSkSSrT7ZJ.png',
    description:'S级第11位的英雄，拥有超合金般的黑色肌肉。极度自信但被饿狼击败后陷入了严重的心理崩溃。曾经是最自恋的英雄，认为自己无人能敌。坚持高强度训练塑造出的完美身材让所有对手恐惧。',
    traits:['黑肤','肌肉男','S级','超合金','自信','心理脆弱','训练狂','健美','第11位'],
    nicknames:['Ikemen Kamen Amai Mask','超合金黑光','超合金'],
    vas:[['桧山修之','']] }],

  // ====== 东京喰种 (5) ======
  [87275, { name:'金木研', anime_title:'东京喰种', image:'https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png',
    description:'原本是普通的大学生，被卷入事件后移植了喰种的赫子而成为半喰种。经历了无数残酷的折磨和蜕变，从温柔少年转变为白发独眼的强大喰种组织首领。名言是"这个世界是错误的"和"1000-7等于多少？"。',
    traits:['白发','独眼喰种','赫子','鳞赫','大学生','文学少年','黑化','喰种首领','悲惨','拷问','吃货','人格分裂'],
    nicknames:['Ken Kaneki','金木研','Kaneki','眼罩喰种','蜈蚣','黑色死神'],
    vas:[['花江夏树','']] }],
  [87277, { name:'雾岛董香', anime_title:'东京喰种', image:'https://s4.anilist.co/file/anilistcdn/character/large/b87277-oUaqrI1iBzu6.png',
    description:'古董咖啡厅的女服务生兼喰种。紫羽赫持有者，性格冷淡但内心温柔。与金木经历了许多生死考验，最终与他结为夫妻并生下一女。战斗力在SS级喰种之上，是金木最坚强的后盾。',
    traits:['紫发','羽赫','咖啡厅','冷淡','温柔','喰种','SS级','金木妻子','坚强','表面冷酷'],
    nicknames:['Touka Kirishima','雾岛董香','Touka','Rabbit'],
    vas:[['雨宫天','']] }],
  [88412, { name:'铃屋什造', anime_title:'东京喰种', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88412-sIOJUnIkyFRe.png',
    description:'CCG特等搜查官，外表中性打扮满身缝合痕迹的天才少年。童年被Big Madam抚养受到严重虐待，性格极具虐待倾向但也渴望被爱。使用镰刀状昆克，战斗方式残酷而华丽。',
    traits:['白发','缝合痕迹','天才搜查官','镰刀昆克','虐待','中性','CCG','特等','悲惨童年','疯狂'],
    nicknames:['Juuzou Suzuya','铃屋什造','Juuzou','13区杰森'],
    vas:[['钉宫理惠','']] }],
  [88421, { name:'永近英良', anime_title:'东京喰种', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88421-F8yaeVfHjwYn.png',
    description:'金木研最好的朋友，童年时代就认识的阳光青年。虽然没有任何特殊能力但头脑极为敏锐，在暗中调查喰种事件的真相。为了保护金木不惜一切，是金木人性不曾完全丧失的关键锚点。',
    traits:['金发','阳光','普通人类','挚友','敏锐','暗助金木','CCC','无能力者','义气'],
    nicknames:['Hideyoshi Nagachika','永近英良','Hide','金木挚友'],
    vas:[['丰永利行','']] }],
  [125884, { name:'龙泽政道', anime_title:'东京喰种', image:'https://s4.anilist.co/file/anilistcdn/character/large/b125884-x9UNA2Lp31pf.jpg',
    description:'CCG二等搜查官，在喰种收容所任务中被青桐树俘虏并改造成独眼喰种。性格扭曲疯狂，内心却仍保留着对过去自我的记忆和悔恨。是喰种与人类矛盾冲突下的悲剧产物。',
    traits:['独眼喰种','前搜查官','扭曲','疯狂','悲剧','改造','CCG','半喰种'],
    nicknames:['Seidou Takizawa','龙泽政道','Taki','菠萝'],
    vas:[['松冈祯丞','']] }],

  // ====== 无职转生 (6) ======
  [88348, { name:'鲁迪乌斯·格雷拉特', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88348-bIe5XnXdRpmX.png',
    description:'34岁尼特族被撞死后转生到剑与魔法世界，保留前世记忆的魔法天才。从婴儿时期就开始修炼，成为无咏唱魔法的开创者。虽然前世是个废柴但今生发誓要"认真活下去"。魔法与剑术双修的全能型天才。',
    traits:['棕发','转生者','魔法天才','无咏唱','原NEET','认真活下去','天才','双修','剑与魔法','家庭'],
    nicknames:['Rudeus Greyrat','鲁迪乌斯','Rudeus','鲁迪'],
    vas:[['内山夕实','']] }],
  [88349, { name:'艾莉丝·伯雷亚斯·格雷拉特', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88349-5dsNUah3oBj8.png',
    description:'阿斯拉王国贵族大小姐，鲁迪乌斯的远亲。个性火爆脾气极差但心地善良。起初完全抗拒学习，在鲁迪乌斯的教导下学会了读写和剑术。后来成长为被称作"狂剑王"的最强女剑士。',
    traits:['红发','大小姐','暴力','火爆','剑士','狂剑王','鲁迪徒弟','傲娇','强大','贵族'],
    nicknames:['Eris Boreas Greyrat','艾莉丝','Eris','狂剑王','暴娇大小姐'],
    vas:[['加隈亚衣','']] }],
  [88350, { name:'洛琪希·米格路迪亚', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88350-QU1iwgZ887U8.png',
    description:'魔族米格路德族的魔法导师，鲁迪乌斯的第一位老师和初恋对象。外表像小学生但实际年龄远大于此，因为该族成年后外貌不变。拥有极高的魔法造诣但极度怕生和不善社交。',
    traits:['蓝发','魔族','魔法导师','幼女体型','怕生','鲁迪老师','初恋','水魔法','孤独','米格路德族'],
    nicknames:['Roxy Migurdia','洛琪希','Roxy','鲁迪老师'],
    vas:[['小原好美','']] }],
  [88346, { name:'希露菲叶特', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88346-h8kCL93AXj4n.png',
    description:'鲁迪乌斯的青梅竹马和第一位朋友。拥有绿色头发和精灵族血统，因被欺负而剪短发打扮成男孩。在鲁迪乌斯的鼓励下变得自信，擅长大范围风属性魔法。最终成为鲁迪乌斯的第一位妻子。',
    traits:['绿发','精灵血统','青梅竹马','伪男','被霸凌','风魔法','鲁迪妻子','害羞','善良'],
    nicknames:['Sylphiette','希露菲叶特','Sylphy','Fitts'],
    vas:[['茅野爱衣','']] }],
  [88351, { name:'瑞杰路德·斯佩路迪亚', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b88351-grqY44xz6bvP.png',
    description:'斯佩路德族的战士，被世人畏惧为"死斑魔"。外表恐怖但内心善良，由于种族被诅咒而长期被人类误解和恐惧。成为鲁迪乌斯的旅行护卫和导师，教会了他战斗技巧和做人的道理。额头的宝石是他的标志。',
    traits:['光头','斯佩路德族','死斑魔','战士','护卫','被误解','善良','导师','红宝石','稳重'],
    nicknames:['Ruijerd Superdia','瑞杰路德','Ruijerd','死斑魔'],
    vas:[['浪川大辅','']] }],
  [137816, { name:'七星静香', anime_title:'无职转生', image:'https://s4.anilist.co/file/anilistcdn/character/large/b137816-ub5QE86fHD3C.png',
    description:'与鲁迪乌斯一样从日本转生而来的少女，但转生的时间和方式不同。在魔法大学中与鲁迪乌斯相遇并成为重要的盟友。拥有关于另一个世界召唤魔法的知识，是连接两个世界秘密的关键人物。',
    traits:['黑发','转生者','日本人','魔法大学','异世界知识','盟友','冷静','召唤魔法'],
    nicknames:['Shizuka Nanahoshi','七星静香','Nanahoshi','静香'],
    vas:[['若山诗音','']] }],

  // ====== 约定的梦幻岛 (5) ======
  [121725, { name:'艾玛', anime_title:'约定的梦幻岛', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121725-LQciVJOjnMVh.png',
    description:'格雷斯菲尔德孤儿院最年长的三人之一，11岁的天才少女。拥有惊人的运动能力和乐观精神，在得知孤儿院的真相后决意带所有家人逃离。坚持"一个都不少的全员逃脱"信念，是集体越狱计划的核心推动者。',
    traits:['橙发','11岁','天才','乐观','全员逃脱','运动全能','领导力','正义','孤儿院','不屈'],
    nicknames:['Emma','艾玛','エマ'],
    vas:[['诸星堇','']] }],
  [121700, { name:'诺曼', anime_title:'约定的梦幻岛', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121700-CRwKIlcBcjbv.jpg',
    description:'孤儿院最年长的三人之一，拥有超群的智力和策略头脑。在得知真相后制定了精密的逃脱计划。深爱艾玛和所有家人，愿意为了大家的自由自我牺牲。在被出货后竟奇迹般生还并成长为更强的存在。',
    traits:['白发','天才','策略家','自我牺牲','冷静','深爱艾玛','孤儿院','智力超群','11岁','腹黑'],
    nicknames:['Norman','诺曼','ノーマン'],
    vas:[['内田真礼','']] }],
  [121724, { name:'雷', anime_title:'约定的梦幻岛', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121724-SJTdODjeO7e6.jpg',
    description:'孤儿院最年长的三人之一，拥有极强的记忆力和信息收集能力。六岁起就知道孤儿院是食用儿的农场却一直假装无知。性格表面冷淡、实际比谁都重情，是艾玛和诺曼最可靠的智囊和伙伴。',
    traits:['黑发','记忆力','冷淡','重情','智囊','孤儿院','信息战','6岁知情','生存主义'],
    nicknames:['Ray','雷','レイ'],
    vas:[['伊濑茉莉也','']] }],
  [121701, { name:'伊莎贝拉', anime_title:'约定的梦幻岛', image:'https://s4.anilist.co/file/anilistcdn/character/large/b121701-hP5hanKRUH9u.png',
    description:'格雷斯菲尔德孤儿院的妈妈，负责管理所有食用儿。外表温柔美丽但内心冷酷，曾是最优秀的妈妈。有着复杂的过去——自己也曾是想逃出孤儿院的食用儿，失败后选择了成为管理者。',
    traits:['黑发','妈妈','孤儿院管理者','冷酷','温柔表象','悲剧过去','前食用儿','复杂','长发'],
    nicknames:['Isabella','伊莎贝拉','妈妈','Isabella'],
    vas:[['甲斐田裕子','']] }],
  [126455, { name:'吉尔达', anime_title:'约定的梦幻岛', image:'https://s4.anilist.co/file/anilistcdn/character/large/b126455-ki6wpr5Un4fF.png',
    description:'孤儿院中年纪较大的孩子之一，性格沉静勇敢。在越狱计划中协助核心三人组收集信息和资源。虽然在体力上不如艾玛但在组织协调方面非常出色，是团队不可或缺的支柱。',
    traits:['黑发','眼镜','沉静','勇敢','组织者','孤儿院','越狱团队','可靠'],
    nicknames:['Gilda','吉尔达','Gilda'],
    vas:[['暂未收录','']] }],

  // ====== 紫罗兰永恒花园 (5) ======
  [90169, { name:'薇尔莉特·伊芙加登', anime_title:'紫罗兰永恒花园', image:'https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png',
    description:'曾是战场上被称为"武器"的少女士兵，在战争结束后成为自动手记人偶——替无法写信的人代笔。拥有机械般美丽和精确度的战斗义肢，但无法理解人类的情感。通过为他人代笔写信慢慢理解了"爱"的含义——这是那位对她说的最后一句话。',
    traits:['金发','蓝色眼瞳','义肢','自动手记人偶','前士兵','武器','代笔','寻找爱','无表情','美丽','机械般精准'],
    nicknames:['Violet Evergarden','薇尔莉特·伊芙加登','Violet','自动手记人偶'],
    vas:[['石川由依','']] }],
  [124790, { name:'吉尔伯特·布干维利亚', anime_title:'紫罗兰永恒花园', image:'https://s4.anilist.co/file/anilistcdn/character/large/b124790-QR7zyemTK0zq.png',
    description:'原莱顿沙夫特里希陆军少佐，在战场上捡到并抚养了薇尔莉特。教她识字和语言，在最后一战中对她说出了"我爱你"并被认为战死。整个故事围绕薇尔莉特寻找这句话含义的旅程展开。绿宝石胸针是两人的信物。',
    traits:['蓝发','少佐','军人','绅士','温柔','捡到薇尔莉特','我爱你','绿宝石','失踪','深情'],
    nicknames:['Gilbert Bougainvillea','吉尔伯特·布干维利亚','Gilbert','少佐'],
    vas:[['浪川大辅','']] }],
  [124799, { name:'克劳迪亚·霍金斯', anime_title:'紫罗兰永恒花园', image:'https://s4.anilist.co/file/anilistcdn/character/large/b124799-htaqVGZd83GW.jpg',
    description:'原陆军中佐，战后创立了CH邮政公司。曾是吉尔伯特的战友，受其临终托付照顾薇尔莉特。性格洒脱不拘小节，给薇尔莉特提供了成为自动手记人偶的机会。是薇尔莉特新人生的第一个引路人。',
    traits:['金发','眼镜','前军人','邮政公司社长','洒脱','引路人','吉尔伯特战友','照顾薇尔莉特'],
    nicknames:['Claudia Hodgins','克劳迪亚·霍金斯','Hodgins','社长'],
    vas:[['子安武人','']] }],
  [124810, { name:'卢克利娅·马尔伯勒', anime_title:'紫罗兰永恒花园', image:'https://s4.anilist.co/file/anilistcdn/character/large/b124810-CuoTUTc7U08r.jpg',
    description:'住在首都的小镇少女，与战后失明的哥哥相依为命。委托薇尔莉特为哥哥写情书的人——希望让哥哥相信远方还有人在等他。这个故事展示了薇尔莉特作为自动手记人偶帮助他人的第一个典型案例。',
    traits:['棕发','少女','妹妹','善良','情书委托','代笔客户','照顾家人'],
    nicknames:['Luculia Marlborough','卢克利娅','Luculia'],
    vas:[['暂未收录','']] }],
  [124787, { name:'卡特莉亚·波德莱尔', anime_title:'紫罗兰永恒花园', image:'https://s4.anilist.co/file/anilistcdn/character/large/b124787-1HuZGawvoejp.jpg',
    description:'CH邮政公司的首席自动手记人偶，也是培训薇尔莉特的导师。拥有丰富的代笔经验和敏锐的文学品味，深受客户信赖。虽然薇尔莉特开始时写得像战报一样但卡特莉亚耐心地引导她。',
    traits:['棕发','自动手记人偶','首席代笔','导师','文学品味','耐心','优雅','资深'],
    nicknames:['Cattleya Baudelaire','卡特莉亚','Cattleya','首席人偶'],
    vas:[['暂未收录','']] }],

  // ====== 夏目友人帐 (3) ======
  [13783, { name:'夏目贵志', anime_title:'夏目友人帐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b13783-FvmhRaCOKzKQ.png',
    description:'从小就看得见妖怪的孤独少年。父母早逝后辗转在亲戚家之间寄宿，因能看到妖怪而被同学排挤。继承了外婆夏目玲子的"友人帐"——一本写满妖怪名字的契约书。与猫咪老师一起将名字还给妖怪们，逐渐找到了自己的归宿和温暖。',
    traits:['棕发','温柔','孤独','见妖能力','友人帐','名字归还','善良','父母早逝','猫老师','外婆玲子'],
    nicknames:['Takashi Natsume','夏目贵志','Natsume','夏目'],
    vas:[['神谷浩史','']] }],
  [13784, { name:'斑', anime_title:'夏目友人帐', image:'https://s4.anilist.co/file/anilistcdn/character/large/13784.jpg',
    description:'被封印在招财猫中的高级妖怪，真名"斑"。平时以肥嘟嘟的三色招财猫形态出现（自称"猫咪老师"），真身是白色巨狼般的威严妖怪。与夏目约定保护他以换取友人帐的所有权，但渐渐真心喜欢上了这个温柔少年。',
    traits:['三色猫','招财猫','白色巨狼','高级妖怪','猫咪老师','贪吃','傲娇','酒鬼','守护','真名斑'],
    nicknames:['Madara','斑','猫咪老师','Nyanko-sensei','斑大人'],
    vas:[['井上和彦','']] }],
  [13886, { name:'夏目玲子', anime_title:'夏目友人帐', image:'https://s4.anilist.co/file/anilistcdn/character/large/b13886-jvXFmldVIkEu.png',
    description:'夏目贵志的外婆，友人帐的创造者。拥有极其强大的灵力，年轻时孤独地在山林中打败妖怪并收集它们的名字。性格被人们传为怪异但实际只是渴望与人交流。已经去世多年，只有妖怪们对她记忆犹新。',
    traits:['棕发','灵力极强','友人帐创造者','孤独','去世','外婆','打败妖怪','温柔','强大'],
    nicknames:['Natsume Reiko','夏目玲子','Reiko','友人帐主人'],
    vas:[['暂未收录','']] }],

  // ====== 四月是你的谎言 (5) ======
  [69407, { name:'有马公生', anime_title:'四月是你的谎言', image:'https://s4.anilist.co/file/anilistcdn/character/large/b69407-eyIvpsFPeARS.png',
    description:'被称为"人体节拍器"的天才钢琴少年，从小在母亲严苛的指导下获奖无数。母亲去世后因心理创伤失去了听到自己钢琴声的能力。直到遇见了自由奔放的小提琴手宫园薰，她教会了他——音乐不是用来取悦别人的，是用来传达心意的。',
    traits:['黑发','眼镜','钢琴天才','人体节拍器','听力丧失','心理创伤','母亲去世','古典音乐','温柔'],
    nicknames:['Kousei Arima','有马公生','Kousei','人体节拍器'],
    vas:[['花江夏树','']] }],
  [69411, { name:'宫园薰', anime_title:'四月是你的谎言', image:'https://s4.anilist.co/file/anilistcdn/character/large/b69411-lxM0FRvWHqlv.png',
    description:'自由奔放的小提琴少女，以充满感情的演奏风格著称。在樱花飞舞的四月遇见了有马公生，改变了彼此的人生。表面上活泼开朗但背负着重病的秘密。她用生命最后的时光教会了公生爱的含义。名言是"你驻足于春色之中"。',
    traits:['金发','蓝色眼瞳','小提琴','自由奔放','重病','乐观','活出精彩','四月','樱花','谎言','天使'],
    nicknames:['Kaori Miyazono','宫园薰','Kaori','四月的小提琴手'],
    vas:[['种田梨沙','']] }],
  [69409, { name:'泽部椿', anime_title:'四月是你的谎言', image:'https://s4.anilist.co/file/anilistcdn/character/large/69409-lq7MFPFTwmBu.png',
    description:'有马公生的青梅竹马和邻居。足球少女，性格热血直率。从小就陪伴在公生身边，暗恋他多年却不敢表白。对音乐并无特殊感情，但对公生的钢琴生涯给予了最朴实的支持。在薰出现后被迫直面自己的感情。',
    traits:['棕发','运动少女','青梅竹马','足球','暗恋','热血','直率','邻居','公生支柱'],
    nicknames:['Tsubaki Sawabe','泽部椿','Tsubaki','青梅竹马'],
    vas:[['佐仓绫音','']] }],
  [69405, { name:'渡边良太', anime_title:'四月是你的谎言', image:'https://s4.anilist.co/file/anilistcdn/character/large/69405-IpsjziJkHrHj.png',
    description:'有马公生和泽部椿的好友，足球部的明星球员。性格阳光开朗，是四人组中的气氛活跃者。对宫园薰抱有好感，总是试图追求她。虽然看起来大大咧咧但非常关心身边的朋友。',
    traits:['棕发','足球','阳光','开朗','薰追求者','好友','气氛担当','运动员'],
    nicknames:['Ryouta Watari','渡边良太','Watari','渡边'],
    vas:[['逢坂良太','']] }],
  [157244, { name:'相座凪', anime_title:'四月是你的谎言', image:'https://s4.anilist.co/file/anilistcdn/character/large/b157244-Hlp5gH8ia6GN.jpg',
    description:'小学生钢琴天才，一直崇拜着"人体节拍器"时代的有马公生。性格傲娇嘴硬，在公生的指导下开始理解音乐的自由和乐趣。是公生成长之后回头帮助下一代的小小象征。',
    traits:['黑发','小学生','钢琴','傲娇','崇拜公生','天才','双马尾','成长'],
    nicknames:['Nagi Aiza','相座凪','Nagi'],
    vas:[['暂未收录','']] }],
]

let count = 0
for (const [id, d] of data) {
  const { error } = await supabase.from('characters').upsert({
    id, name: d.name, anime_title: d.anime_title, image: d.image,
    description: d.description, traits: d.traits, nicknames: d.nicknames,
  }, { onConflict: 'id' })
  if (d.vas) {
    await supabase.from('voice_actors').delete().eq('character_id', id)
    for (const [name, img] of d.vas) {
      await supabase.from('voice_actors').insert({ character_id: id, name, image: img || '', language: '日语' })
    }
  }
  process.stdout.write(error ? '❌' : '+')
  count++
}
console.log('\n重建 search_text...')
const { data: chars } = await supabase.from('characters').select('id, name, anime_title, nicknames, traits, voice_actors(name)')
for (const c of chars||[]) {
  const st = [c.name, c.anime_title||'', ...(c.nicknames||[]), ...(c.traits||[]), ...(c.voice_actors||[]).map(v=>v.name)].join(' ')
  await supabase.from('characters').update({ search_text: st }).eq('id', c.id)
}
console.log('✅', count, '个角色')
