import { createClient } from '@supabase/supabase-js'

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY)
const api = 'https://graphql.anilist.co'
const groups = [
 [71, '全金属狂潮', ['军事', '校园', '机甲']], [8934, 'STAR DRIVER 跨越星际', ['校园', '超能力', '机甲']], [1289, '机动警察', ['警察', '近未来', '机甲']], [15863, '银河机攻队 MAJESTIC PRINCE', ['太空', '基因改造', '机甲']], [20881, '重装武器', ['战争', '兵器', '战术']], [12471, '交响诗篇AO', ['青春', '科幻', '机甲']], [949, '飞跃巅峰', ['宇宙', '科学', '超级系']], [6772, '破刃之剑', ['战争', '冷兵器', '机甲']], [16668, '革命机Valvrave', ['校园', '政治', '机甲']], [99423, 'DARLING in the FRANXX', ['青春', '反乌托邦', '机甲']], [218, '机动战舰抚子号', ['太空歌剧', '喜剧', '机甲']], [3572, '超时空要塞F', ['歌唱', '变形机甲', '太空']], [978, '真盖塔机器人 世界最后之日', ['合体机器人', '热血', '末世']], [890, '勇者王GaoGaiGar', ['勇者', '合体机器人', '热血']], [878, 'Zegapain', ['虚拟现实', '科幻', '机甲']], 
]
const query = `query($id:Int){Media(id:$id,type:ANIME){characters(page:1,perPage:50,sort:ROLE){edges{role node{id name{full native} image{large}} voiceActors(language:JAPANESE){name{full} image{large}}}}}}`
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
function makeDescription(name, title, themes, role) { return `${name}是《${title}》中的${role === 'MAIN' ? '核心角色' : '重要配角'}。作品围绕${themes.join('、')}等机甲科幻主题展开，角色在战斗、任务或复杂关系中承担独特作用。随着故事推进，${name}面对战争、理想与责任的选择，并与队友和对手共同推动剧情发展，展现作品对科技、人性和未来社会的思考。` }
async function fetchGroup([id, title, themes]) { const r = await fetch(api, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables: { id } }) }); const p = await r.json(); const rows = []; for (const [i, e] of (p.data?.Media?.characters?.edges || []).entries()) { const image = e.node.image?.large; if (!image?.includes('anilistcdn') || image.includes('/default.')) continue; const name = e.node.name.native || e.node.name.full; const nick = [...new Set([e.node.name.full, e.node.name.native, name].filter(Boolean))]; const traits = [...new Set([...themes, e.role === 'MAIN' ? '主要角色' : '重要配角', '机甲驾驶员', '剧情推动者', '核心人物', '日本动画', '科幻作品', `角色序位${i + 1}`])]; const c = { id: e.node.id, name, image, description: makeDescription(name, title, themes, e.role), anime_title: title, nicknames: nick, traits }; const a = e.voiceActors?.find((v) => v?.name?.full && v.image?.large?.includes('anilistcdn')); const voiceActor = a ? { character_id: c.id, name: a.name.full, image: a.image.large, language: '日语' } : null; rows.push({ character: { ...c, search_text: [name, title, ...nick, ...traits, ...(voiceActor ? [voiceActor.name] : [])].join(' ') }, voiceActor }) } if (rows.length < 5) throw new Error(`${title} 有效角色不足`); return rows }
async function main() { const titles = new Set(); for (let offset = 0; ; offset += 1000) { const q = await supabase.from('characters').select('anime_title').range(offset, offset + 999); if (q.error) throw Error(q.error.message); for (const row of q.data || []) titles.add(row.anime_title); if (!q.data || q.data.length < 1000) break } const duplicate = groups.find(([, title]) => titles.has(title)); if (duplicate) throw Error(`数据库已存在：${duplicate[1]}`); const all = []; for (const group of groups) { all.push(...await fetchGroup(group)); await sleep(750) } const existing = await supabase.from('characters').select('id').in('id', all.map((x) => x.character.id)); if (existing.error) throw Error(existing.error.message); const taken = new Set((existing.data || []).map((x) => x.id)); const unique = []; const seen = new Set(); for (const row of all) if (!taken.has(row.character.id) && !seen.has(row.character.id)) { seen.add(row.character.id); unique.push(row) } const counts = new Map(); for (const row of unique) counts.set(row.character.anime_title, (counts.get(row.character.anime_title) || 0) + 1); const deficient = [...counts].filter(([, count]) => count < 5); if (deficient.length) throw Error(`去重后作品不足：${deficient.map(([title, count]) => `${title}=${count}`).join(', ')}`); const characters = unique.map((x) => x.character); const actors = unique.map((x) => x.voiceActor).filter(Boolean); let q = await supabase.from('characters').insert(characters); if (q.error) throw Error(q.error.message); if (actors.length) { q = await supabase.from('voice_actors').insert(actors); if (q.error) throw Error(q.error.message) } console.log(`Synced ${characters.length} characters across ${groups.length} mecha anime; ${actors.length} Japanese voice actors.`) }
main().catch((error) => { console.error(error.message); process.exit(1) })
