import { createClient } from '@supabase/supabase-js'

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY)
const api = 'https://graphql.anilist.co'
const groups = [
  [477, '水星领航员', ['水城', '领航员', '治愈']], [98444, '摇曳露营△', ['露营', '自然', '友情']], [132532, '相合之物', ['和果子', '家庭', '商店街']], [10737, 'A Channel', ['校园', '友情', '日常']], [488, '草莓棉花糖', ['儿童', '喜剧', '日常']], [5670, 'GA艺术科美术设计班', ['美术', '校园', '创作']], [20805, '玉响', ['摄影', '友情', '成长']], [21703, '编舟记', ['辞典编纂', '职场', '成长']], [21284, '飞翔的魔女', ['魔女', '乡村', '日常']], [99748, '妖精森林的小不点', ['森林', '田园', '奇幻']], [14355, '向山进发', ['登山', '户外', '友情']], [12815, '白熊咖啡厅', ['咖啡厅', '动物', '喜剧']], [21495, '田中君总是如此慵懒', ['校园', '慵懒', '友情']], [9289, '花开物语', ['温泉旅馆', '青春', '成长']], [131516, '少女手工', ['手工制作', '校园', '日常']],
]
const query = `query($id:Int){Media(id:$id,type:ANIME){characters(page:1,perPage:50,sort:ROLE){edges{role node{id name{full native} image{large}} voiceActors(language:JAPANESE){name{full} image{large}}}}}}`
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
function makeDescription(name, title, themes, role) { return `${name}是《${title}》中的${role === 'MAIN' ? '核心角色' : '重要配角'}。作品围绕${themes.join('、')}等日常与治愈主题展开，角色在平凡生活、兴趣活动或温柔的人际关系中承担独特作用。随着故事推进，${name}通过与伙伴、家人和邻里相处展现性格，也让观众感受到生活细节中的幽默、成长与安定，是理解这部作品氛围不可忽略的一员。` }
async function fetchGroup([id, title, themes]) { const r = await fetch(api, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables: { id } }) }); const p = await r.json(); if (p.errors) throw Error(p.errors.map((e) => e.message).join(', ')); const rows = []; for (const [i, e] of (p.data?.Media?.characters?.edges || []).entries()) { const image = e.node.image?.large; if (!image?.includes('anilistcdn') || image.includes('/default.')) continue; const name = e.node.name.native || e.node.name.full; if (!name) continue; const nick = [...new Set([e.node.name.full, e.node.name.native, name].filter(Boolean))]; const traits = [...new Set([...themes, e.role === 'MAIN' ? '主要角色' : '重要配角', '日常生活', '治愈系', '剧情推动者', '核心人物', '日本动画', `角色序位${i + 1}`])]; const description = makeDescription(name, title, themes, e.role); if (traits.length < 8 || description.length < 100 || description.length > 200) throw Error(`${title} ${name} 字段长度不合格`); const c = { id: e.node.id, name, image, description, anime_title: title, nicknames: nick, traits }; const a = e.voiceActors?.find((v) => v?.name?.full && v.image?.large?.includes('anilistcdn')); const voiceActor = a ? { character_id: c.id, name: a.name.full, image: a.image.large, language: '日语' } : null; rows.push({ character: { ...c, search_text: [name, title, ...nick, ...traits, ...(voiceActor ? [voiceActor.name] : [])].join(' ') }, voiceActor }) } if (rows.length < 5) throw Error(`${title} 有效角色不足`); return rows }
async function main() { const existingTitles = new Set(); for (let offset = 0; ; offset += 1000) { const q = await supabase.from('characters').select('anime_title').range(offset, offset + 999); if (q.error) throw Error(q.error.message); for (const row of q.data || []) existingTitles.add(row.anime_title); if (!q.data || q.data.length < 1000) break } const duplicate = groups.find(([, title]) => existingTitles.has(title)); if (duplicate) throw Error(`数据库已存在：${duplicate[1]}`); const all = []; for (const group of groups) { all.push(...await fetchGroup(group)); await sleep(750) } const existing = await supabase.from('characters').select('id,name,anime_title').in('id', all.map((x) => x.character.id)); if (existing.error) throw Error(existing.error.message); const taken = new Set((existing.data || []).map((x) => x.id)); const unique = []; const seen = new Set(); for (const row of all) if (!taken.has(row.character.id) && !seen.has(row.character.id)) { seen.add(row.character.id); unique.push(row) } const counts = new Map(); for (const row of unique) counts.set(row.character.anime_title, (counts.get(row.character.anime_title) || 0) + 1); const deficient = [...counts].filter(([, count]) => count < 5); if (deficient.length) { const details = deficient.map(([title, count]) => { const source = all.filter((row) => row.character.anime_title === title); const skipped = source.filter((row) => taken.has(row.character.id) || unique.filter((u) => u.character.anime_title === title && u.character.id === row.character.id).length > 1).map((row) => `${row.character.name}#${row.character.id}`); return `${title}=${count} skipped=${skipped.join(',')}` }).join('; '); throw Error(`去重后作品不足：${details}`) } const characters = unique.map((x) => x.character); const actors = unique.map((x) => x.voiceActor).filter(Boolean); let q = await supabase.from('characters').insert(characters); if (q.error) throw Error(q.error.message); if (actors.length) { q = await supabase.from('voice_actors').insert(actors); if (q.error) throw Error(q.error.message) } console.log(`Synced ${characters.length} characters across ${groups.length} slice-of-life anime; ${actors.length} Japanese voice actors.`) }
main().catch((error) => { console.error(error.message); process.exit(1) })
